/* Generated by `npm run build:widgets`. Do not edit directly. */
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// widgets/starvation_rescue/src/api.ts
var api_exports = {};
__export(api_exports, {
  createStarvationRescue: () => createStarvationRescue,
  getStarvationRescueDevices: () => getStarvationRescueDevices,
  previewStarvationRescue: () => previewStarvationRescue
});
module.exports = __toCommonJS(api_exports);

// packages/shared-domain/src/planStarvation.ts
var STARVATION_RESCUE_WIDGET_COPY = {
  // List header — names what the widget SHOWS (the devices PELS is holding back
  // via the daily budget), not an action the user takes. Shown only when at
  // least one device is held back; the calm empty state stands alone.
  headerTitle: "Held-back devices",
  // Empty (calm) state — nothing is held back. This is the steady, good state.
  emptySubtitle: "No device is being held back right now.",
  // Transient "wiring up to Homey" state, distinct from a hard load failure.
  notReady: "Connecting to Homey\u2026",
  loadError: "Could not load devices. Try again later.",
  // Row status-chip word. The widget appends "· N min". Cause-specific so the
  // chip never overclaims: only budget rows (the releasable "Let it run now"
  // state) say "Held back"; capacity rows say "Waiting" (physically held — the
  // hard cap is not a tuning knob, feedback_hard_cap_is_physical). User-facing
  // register only — no "starvation" jargon.
  starvedChip: "Held back",
  waitingChip: "Waiting",
  // Rescue affordance (budget-caused rows only). "Let it run now" is device-
  // scoped — it releases THIS device from the daily budget so it runs now,
  // rather than promising house power. The rescue is a bounded near-term run
  // (the confirm sheet surfaces the "By {time}" timing prominently).
  rescueButton: "Let it run now",
  // Informational note on capacity rows — they get NO rescue affordance. Honest
  // about why, without implying the user can raise the cap. Matches the canonical
  // "Waiting for available power" wording the overview and the row subtext use,
  // so the capacity story reads the same everywhere.
  capacityNote: "Waiting for available power.",
  // A budget-held device that already has a smart task: shown in the list (so the
  // user sees it is held back) but with no rescue button — its own task is what
  // brings it to target, so a one-shot rescue would only get in the way.
  smartTaskNote: "Its smart task will bring it back.",
  // Rescue confirm sheet.
  // Names the consequence honestly per the money-action guardrail: the rescue
  // lets this device go over today's budget so it reaches its normal target.
  rescueConsequence: "This lets the device use power beyond today\u2019s budget until it reaches its normal target.",
  rescueConfirmButton: "Confirm",
  backButton: "Back",
  scheduledLabel: "Scheduled",
  // Deadline lead for the when-line ("By 17:00"): the rescue reaches the normal
  // target BY this near-term time. Distinct from the create widget's "Ready by"
  // (a user-chosen time) — this is a fixed near-term horizon, so "By" reads
  // truer than "Ready by".
  byLabel: "By",
  energyLabel: "Energy",
  // Same in-isolation caveat the create widget uses — the estimate ignores
  // re-plans and competing tasks.
  estimateCaveat: "Estimate \u2014 the actual run may differ as prices and other tasks change.",
  // Heading for the read-only "what this grants" summary on the confirm sheet.
  // Reuses the create widget's canonical "Extra permissions" wording (via
  // SMART_TASK_EXTRA_PERMISSION_LABELS for the line items) so the two surfaces
  // describe the same permissions identically; here it is informational, not a
  // set of toggles — the rescue always grants both.
  extraPermissionsTitle: "Extra permissions",
  // Factual at-cap honesty signal. The in-isolation preview can show the device
  // running now, but if the house is already pressed against the physical hard
  // cap there is no room until something frees up. Names the real measured
  // fact (at the hard cap), NOT a prompt to raise it — the hard cap is physical
  // (feedback_hard_cap_is_physical). Pairs with the "Running as soon as there’s
  // room" flash for the same honesty when the rescue is committed.
  atCapNote: "Your hard cap is maxed out right now, so it may wait for room before running.",
  // Preview couldn't be projected (no prices yet, missing reading, price
  // optimisation off). Distinct from a hard error.
  previewUnavailable: "Can\u2019t preview this yet \u2014 PELS needs more current data for this window.",
  rescuePending: "Setting up\u2026",
  // Two honest success flashes, branched on whether the projected plan actually
  // runs the device now. The rescue grants the device priority over lower-
  // priority loads (within the physical hard cap) AND lifts today's budget, but
  // if the house is already at the cap with nothing lower-priority to displace,
  // power isn't instant — so don't promise "on the way" unconditionally.
  rescueDone: "Power on the way",
  rescueDoneQueued: "Running as soon as there\u2019s room",
  rescueError: "Could not let it run now. Try again.",
  // The previewed deadline slipped past while the user lingered — retryable.
  deadlinePassed: "That timing just passed. Try again."
};
var STARVATION_RESCUE_DANGER_THRESHOLD_MS = 30 * 6e4;
var starvationRowOffersRescue = (cause) => cause === "budget";
var ONE_HOUR_MS = 60 * 60 * 1e3;
var scheduledHoursIncludeCurrentHour = (scheduledHours, nowMs) => {
  const currentHourStartMs = Math.floor(nowMs / ONE_HOUR_MS) * ONE_HOUR_MS;
  return scheduledHours.some((hour) => hour.startsAtMs === currentHourStartMs);
};

// packages/shared-domain/src/smartTaskDeadlineFormat.ts
var HOUR_MS = 60 * 60 * 1e3;
var DAY_MS = 24 * HOUR_MS;
var formatLocalHHMMFallback = (date) => `${String(date.getHours()).padStart(2, "0")}:${String(date.getMinutes()).padStart(2, "0")}`;
var formatLocalHHMM = (ms, timeZone) => {
  const date = new Date(ms);
  if (!Number.isFinite(date.getTime())) return "";
  try {
    return new Intl.DateTimeFormat("en-GB", {
      hour: "2-digit",
      minute: "2-digit",
      hour12: false,
      timeZone: timeZone ?? void 0
    }).format(date);
  } catch {
    return formatLocalHHMMFallback(date);
  }
};
var calendarDayIndex = (ms, timeZone) => {
  try {
    const ymd = new Intl.DateTimeFormat("en-CA", {
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
      timeZone: timeZone ?? void 0
    }).format(new Date(ms));
    const [y, m, d] = ymd.split("-").map(Number);
    if (!Number.isFinite(y) || !Number.isFinite(m) || !Number.isFinite(d)) {
      throw new Error("unexpected en-CA date parts");
    }
    return Math.round(Date.UTC(y, m - 1, d) / DAY_MS);
  } catch {
    const date = new Date(ms);
    return Math.round(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()) / DAY_MS);
  }
};
var formatSmartTaskDeadlineLong = (ms, nowMs, timeZone) => {
  const date = new Date(ms);
  if (!Number.isFinite(date.getTime())) return "";
  const timePart = formatLocalHHMM(ms, timeZone);
  const dayDiff = calendarDayIndex(ms, timeZone) - calendarDayIndex(nowMs, timeZone);
  if (dayDiff === 0) return `Today ${timePart}`;
  if (dayDiff === 1) return `Tomorrow ${timePart}`;
  try {
    if (dayDiff >= -6 && dayDiff <= 6) {
      const weekday = new Intl.DateTimeFormat("en-GB", {
        weekday: "short",
        timeZone: timeZone ?? void 0
      }).format(date);
      return `${weekday} ${timePart}`;
    }
    const dayMonth = new Intl.DateTimeFormat("en-GB", {
      day: "numeric",
      month: "short",
      timeZone: timeZone ?? void 0
    }).format(date);
    return `${dayMonth} ${timePart}`;
  } catch {
    return formatLocalHHMMFallback(date);
  }
};
var hoursAreContiguous = (hours) => {
  for (let i = 1; i < hours.length; i += 1) {
    if (hours[i].startsAtMs - hours[i - 1].startsAtMs !== HOUR_MS) return false;
  }
  return true;
};
var formatScheduledHoursWindow = (scheduledHours, timeZone) => {
  if (scheduledHours.length === 0) return null;
  if (scheduledHours.length === 1) {
    return formatLocalHHMM(scheduledHours[0].startsAtMs, timeZone);
  }
  if (hoursAreContiguous(scheduledHours)) {
    const first = formatLocalHHMM(scheduledHours[0].startsAtMs, timeZone);
    const lastStart = scheduledHours[scheduledHours.length - 1].startsAtMs;
    const end = formatLocalHHMM(lastStart + HOUR_MS, timeZone);
    return `${first}\u2013${end}`;
  }
  return scheduledHours.map((hour) => formatLocalHHMM(hour.startsAtMs, timeZone)).join(", ");
};

// widgets/starvation_rescue/src/starvationRescueWidgetPayload.ts
var buildStarvationRescueDevicesPayload = (input) => {
  const devices = Array.isArray(input.devices) ? input.devices : [];
  if (devices.length === 0) {
    return { state: "empty", subtitle: STARVATION_RESCUE_WIDGET_COPY.emptySubtitle };
  }
  return { state: "ready", devices };
};

// widgets/starvation_rescue/src/api.ts
var RESCUE_DEADLINE_HORIZON_MS = 3 * 60 * 60 * 1e3;
var readTimeZone = (homey) => {
  const tz = homey.clock?.getTimezone?.();
  return typeof tz === "string" && tz.length > 0 ? tz : "UTC";
};
var parseRescueRequest = (body) => {
  if (!body || typeof body !== "object" || Array.isArray(body)) return null;
  const candidate = body;
  const deviceId = typeof candidate.deviceId === "string" ? candidate.deviceId.trim() : "";
  if (!deviceId) return null;
  const deadlineAtMs = typeof candidate.deadlineAtMs === "number" && Number.isFinite(candidate.deadlineAtMs) ? candidate.deadlineAtMs : void 0;
  return deadlineAtMs === void 0 ? { deviceId } : { deviceId, deadlineAtMs };
};
var resolveRescuableDevice = (app) => {
  const devices = typeof app?.getStarvedRescueDevices === "function" ? app.getStarvedRescueDevices() : null;
  if (devices === null) {
    return () => ({ ok: false, reason: "unavailable" });
  }
  const byId = new Map(devices.map((device) => [device.deviceId, device]));
  return (deviceId) => {
    const device = byId.get(deviceId);
    if (!device || !starvationRowOffersRescue(device.cause) || device.hasSmartTask) {
      return { ok: false, reason: "not_rescuable" };
    }
    const target = device.intendedNormalTargetC;
    if (target === null || !Number.isFinite(target)) {
      return { ok: false, reason: "no_target" };
    }
    return { ok: true, targetTemperatureC: target };
  };
};
var buildRescueCandidate = (targetTemperatureC, deadlineAtMs) => ({
  kind: "temperature",
  enforcement: "soft",
  targetTemperatureC,
  deadlineAtMs,
  // The rescue requests BOTH permissions; the create engine's
  // `gateCandidateExtraPermissions` keeps `exemptFromBudget` for any device and
  // the `limitLowerPriorityDevices` grant only where it has effect (stepped-load
  // + top priority), so the widget never needs the device profile here.
  rescue: { exemptFromBudget: "always", limitLowerPriorityDevices: "always" }
});
var previewReject = (reason) => ({
  ok: false,
  reason
});
var createReject = (reason) => ({
  ok: false,
  reason
});
var mapAppReason = (reason) => {
  if (reason === "device_not_found") return "device_not_found";
  if (reason === "device_not_planned") return "device_not_planned";
  if (reason === "device_not_eligible") return "device_not_eligible";
  if (reason === "write_conflict" || reason === "write_refused") return "write_conflict";
  return "invalid_candidate";
};
var getStarvationRescueDevices = async ({ homey }) => {
  const devices = typeof homey.app?.getStarvedRescueDevices === "function" ? homey.app.getStarvedRescueDevices() : null;
  return buildStarvationRescueDevicesPayload({ devices });
};
var previewStarvationRescue = async ({ homey, body }) => {
  const request = parseRescueRequest(body);
  if (!request) return previewReject("invalid_request");
  if (typeof homey.app?.previewStarvationRescuePlan !== "function") return previewReject("unavailable");
  const rescuable = resolveRescuableDevice(homey.app)(request.deviceId);
  if (!rescuable.ok) return previewReject(rescuable.reason);
  const timeZone = readTimeZone(homey);
  const nowMs = Date.now();
  const candidate = buildRescueCandidate(rescuable.targetTemperatureC, nowMs + RESCUE_DEADLINE_HORIZON_MS);
  const { estimate, deadlineAtMs } = homey.app.previewStarvationRescuePlan(request.deviceId, candidate);
  return {
    ok: true,
    deadlineAtMs,
    deadlineLabel: formatSmartTaskDeadlineLong(deadlineAtMs, nowMs, timeZone),
    scheduledWindowLabel: formatScheduledHoursWindow(estimate.scheduledHours, timeZone),
    estimate
  };
};
var createStarvationRescue = async ({ homey, body }) => {
  const request = parseRescueRequest(body);
  if (!request) return createReject("invalid_request");
  if (typeof homey.app?.rescueDeviceWithBudgetExemption !== "function") return createReject("unavailable");
  const rescuable = resolveRescuableDevice(homey.app)(request.deviceId);
  if (!rescuable.ok) return createReject(rescuable.reason);
  const nowMs = Date.now();
  const deadlineAtMs = request.deadlineAtMs ?? nowMs + RESCUE_DEADLINE_HORIZON_MS;
  if (deadlineAtMs <= nowMs || deadlineAtMs > nowMs + RESCUE_DEADLINE_HORIZON_MS) {
    return createReject("deadline_passed");
  }
  const candidate = buildRescueCandidate(rescuable.targetTemperatureC, deadlineAtMs);
  const result = homey.app.rescueDeviceWithBudgetExemption(request.deviceId, candidate);
  if (!result.ok) return createReject(mapAppReason(result.reason));
  const post = homey.app.previewStarvationRescuePlan?.(request.deviceId, candidate);
  return {
    ok: true,
    runsCurrentHour: post ? scheduledHoursIncludeCurrentHour(post.estimate.scheduledHours, nowMs) : false
  };
};
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  createStarvationRescue,
  getStarvationRescueDevices,
  previewStarvationRescue
});
