/* Generated by `npm run build:widgets`. Do not edit directly. */
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// widgets/starvation_rescue/src/starvationRescueWidgetPayload.ts
var starvationRescueWidgetPayload_exports = {};
__export(starvationRescueWidgetPayload_exports, {
  buildStarvationRescueDevicesPayload: () => buildStarvationRescueDevicesPayload
});
module.exports = __toCommonJS(starvationRescueWidgetPayload_exports);

// packages/shared-domain/src/planStarvation.ts
var STARVATION_RESCUE_WIDGET_COPY = {
  // Empty (calm) state — nothing is starved. This is the steady, good state.
  emptySubtitle: "No device is being held back right now.",
  // Transient "wiring up to Homey" state, distinct from a hard load failure.
  notReady: "Connecting to Homey\u2026",
  loadError: "Could not load devices. Try again later.",
  // Row status chip prefix. The widget appends "· N min".
  starvedChip: "Starved",
  // Rescue affordance (budget-caused rows only). "Use budget now" is honest that
  // the action spends today's budget rather than promising instant delivery —
  // the rescue is a bounded near-term run, not an immediate power switch (the
  // confirm sheet surfaces the "By {time}" timing prominently).
  rescueButton: "Use budget now",
  // Informational note on capacity / manual / external rows — they get NO rescue
  // affordance. Honest about why, without implying the user can raise the cap.
  // Matches the canonical "Waiting for available power" wording the overview and
  // the row subtext use, so the capacity story reads the same everywhere.
  capacityNote: "Waiting for available power.",
  manualNote: "Under manual control.",
  externalNote: "Waiting on an external service.",
  // Rescue confirm sheet.
  // Names the consequence honestly per the money-action guardrail: the rescue
  // lets this device go over today's budget so it reaches its normal target.
  rescueConsequence: "This lets the device use power beyond today\u2019s budget until it reaches its normal target.",
  rescueConfirmButton: "Confirm",
  backButton: "Back",
  scheduledLabel: "Scheduled",
  // Deadline lead for the when-line ("By 17:00"): the rescue reaches the normal
  // target BY this near-term time. Distinct from the create widget's "Ready by"
  // (a user-chosen time) — this is a fixed near-term horizon, so "By" reads
  // truer than "Ready by".
  byLabel: "By",
  energyLabel: "Energy",
  // Same in-isolation caveat the create widget uses — the estimate ignores
  // re-plans and competing tasks.
  estimateCaveat: "Estimate \u2014 the actual run may differ as prices and other tasks change.",
  // Preview couldn't be projected (no prices yet, missing reading, price
  // optimisation off). Distinct from a hard error.
  previewUnavailable: "Can\u2019t preview this yet \u2014 no prices published for this window yet.",
  rescuePending: "Setting up\u2026",
  rescueDone: "Power on the way",
  rescueError: "Could not set up the rescue. Try again.",
  // The previewed deadline slipped past while the user lingered — retryable.
  deadlinePassed: "That timing just passed. Try again."
};
var STARVATION_RESCUE_DANGER_THRESHOLD_MS = 30 * 6e4;

// widgets/starvation_rescue/src/starvationRescueWidgetPayload.ts
var buildStarvationRescueDevicesPayload = (input) => {
  const devices = Array.isArray(input.devices) ? input.devices : [];
  if (devices.length === 0) {
    return { state: "empty", subtitle: STARVATION_RESCUE_WIDGET_COPY.emptySubtitle };
  }
  return { state: "ready", devices };
};
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  buildStarvationRescueDevicesPayload
});
