/* Generated by `npm run build:widgets`. Do not edit directly. */
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// widgets/starvation_rescue/src/starvationRescueWidgetPayload.ts
var starvationRescueWidgetPayload_exports = {};
__export(starvationRescueWidgetPayload_exports, {
  buildStarvationRescueDevicesPayload: () => buildStarvationRescueDevicesPayload
});
module.exports = __toCommonJS(starvationRescueWidgetPayload_exports);

// packages/shared-domain/src/planStarvation.ts
var STARVATION_RESCUE_WIDGET_COPY = {
  // List header — names what the widget SHOWS (the devices PELS is holding back
  // via the daily budget), not an action the user takes. Shown only when at
  // least one device is held back; the calm empty state stands alone.
  headerTitle: "Held-back devices",
  // Empty (calm) state — nothing is held back. This is the steady, good state.
  emptySubtitle: "No device is being held back right now.",
  // Transient "wiring up to Homey" state, distinct from a hard load failure.
  notReady: "Connecting to Homey\u2026",
  loadError: "Could not load devices. Try again later.",
  // Row status-chip word. The widget appends "· N min". Cause-specific so the
  // chip never overclaims: only budget rows (the releasable "Let it run now"
  // state) say "Held back"; capacity rows say "Waiting" (physically held — the
  // hard cap is not a tuning knob, feedback_hard_cap_is_physical). User-facing
  // register only — no "starvation" jargon.
  starvedChip: "Held back",
  waitingChip: "Waiting",
  // Rescue affordance (budget-caused rows only). "Let it run now" is device-
  // scoped — it releases THIS device from the daily budget so it runs now,
  // rather than promising house power. The rescue is a bounded near-term run
  // (the confirm sheet surfaces the "By {time}" timing prominently).
  rescueButton: "Let it run now",
  // Informational note on capacity rows — they get NO rescue affordance. Honest
  // about why, without implying the user can raise the cap. Matches the canonical
  // "Waiting for available power" wording the overview and the row subtext use,
  // so the capacity story reads the same everywhere.
  capacityNote: "Waiting for available power.",
  // A budget-held device that already has a smart task: shown in the list (so the
  // user sees it is held back) but with no rescue button — its own task is what
  // brings it to target, so a one-shot rescue would only get in the way.
  smartTaskNote: "Its smart task will bring it back.",
  // Rescue confirm sheet.
  // Names the consequence honestly per the money-action guardrail: the rescue
  // lets this device go over today's budget so it reaches its normal target.
  rescueConsequence: "This lets the device use power beyond today\u2019s budget until it reaches its normal target.",
  rescueConfirmButton: "Confirm",
  backButton: "Back",
  scheduledLabel: "Scheduled",
  // Deadline lead for the when-line ("By 17:00"): the rescue reaches the normal
  // target BY this near-term time. Distinct from the create widget's "Ready by"
  // (a user-chosen time) — this is a fixed near-term horizon, so "By" reads
  // truer than "Ready by".
  byLabel: "By",
  energyLabel: "Energy",
  // Same in-isolation caveat the create widget uses — the estimate ignores
  // re-plans and competing tasks.
  estimateCaveat: "Estimate \u2014 the actual run may differ as prices and other tasks change.",
  // Preview couldn't be projected (no prices yet, missing reading, price
  // optimisation off). Distinct from a hard error.
  previewUnavailable: "Can\u2019t preview this yet \u2014 PELS needs more current data for this window.",
  rescuePending: "Setting up\u2026",
  // Two honest success flashes, branched on whether the projected plan actually
  // runs the device now. The rescue grants the device priority over lower-
  // priority loads (within the physical hard cap) AND lifts today's budget, but
  // if the house is already at the cap with nothing lower-priority to displace,
  // power isn't instant — so don't promise "on the way" unconditionally.
  rescueDone: "Power on the way",
  rescueDoneQueued: "Running as soon as there\u2019s room",
  rescueError: "Could not set up the rescue. Try again.",
  // The previewed deadline slipped past while the user lingered — retryable.
  deadlinePassed: "That timing just passed. Try again."
};
var STARVATION_RESCUE_DANGER_THRESHOLD_MS = 30 * 6e4;
var ONE_HOUR_MS = 60 * 60 * 1e3;

// widgets/starvation_rescue/src/starvationRescueWidgetPayload.ts
var buildStarvationRescueDevicesPayload = (input) => {
  const devices = Array.isArray(input.devices) ? input.devices : [];
  if (devices.length === 0) {
    return { state: "empty", subtitle: STARVATION_RESCUE_WIDGET_COPY.emptySubtitle };
  }
  return { state: "ready", devices };
};
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  buildStarvationRescueDevicesPayload
});
