/* Generated by `npm run build:widgets`. Do not edit directly. */
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// widgets/smart_tasks/src/smartTasksWidgetPayload.ts
var smartTasksWidgetPayload_exports = {};
__export(smartTasksWidgetPayload_exports, {
  EMPTY_SUBTITLE_DEFAULT: () => EMPTY_SUBTITLE_DEFAULT,
  ENDED_ROW_CAP: () => ENDED_ROW_CAP,
  ENDED_WINDOW_MS: () => ENDED_WINDOW_MS,
  ROW_CAP: () => ROW_CAP,
  buildSmartTasksWidgetPayload: () => buildSmartTasksWidgetPayload
});
module.exports = __toCommonJS(smartTasksWidgetPayload_exports);

// packages/shared-domain/src/deferredPlanHistoryChartData.ts
var HOUR_MS = 60 * 60 * 1e3;
var integratePlannedStaircase = (snapshot, anchorValue, anchorAtMs, windowEndMs, capValue = null) => {
  const kwhPerUnitMean = snapshot.kwhPerUnitMean ?? 0;
  if (kwhPerUnitMean <= 0) return [];
  const effectiveCap = capValue === null ? null : Math.max(capValue, anchorValue);
  const sortedHours = [...snapshot.hours].sort((a, b) => a.startsAtMs - b.startsAtMs);
  const points = [
    { atMs: anchorAtMs, value: anchorValue }
  ];
  let cumulativeProgress = anchorValue;
  let lastAnchorAtMs = anchorAtMs;
  for (const hour of sortedHours) {
    const endOfHour = Math.min(windowEndMs, hour.startsAtMs + HOUR_MS);
    if (endOfHour <= anchorAtMs) continue;
    const plannedKWh = Number.isFinite(hour.plannedKWh) ? Math.max(0, hour.plannedKWh) : 0;
    const coverStartMs = hour.coversFromMs ?? hour.startsAtMs;
    const coveredSpanMs = endOfHour - coverStartMs;
    const postAnchorFraction = coveredSpanMs > 0 ? Math.max(0, Math.min(1, (endOfHour - Math.max(anchorAtMs, coverStartMs)) / coveredSpanMs)) : 1;
    if (hour.startsAtMs > lastAnchorAtMs) {
      points.push({ atMs: hour.startsAtMs, value: cumulativeProgress });
    }
    cumulativeProgress += plannedKWh * postAnchorFraction / kwhPerUnitMean;
    if (effectiveCap !== null && cumulativeProgress > effectiveCap) cumulativeProgress = effectiveCap;
    points.push({ atMs: endOfHour, value: cumulativeProgress });
    lastAnchorAtMs = endOfHour;
  }
  return points;
};
var observedValueAt = (observed, atMs) => {
  let before = null;
  for (const point of observed) {
    if (point.atMs <= atMs) {
      before = point;
      continue;
    }
    if (before === null) return null;
    if (point.atMs === before.atMs) return before.value;
    const fraction = (atMs - before.atMs) / (point.atMs - before.atMs);
    return before.value + (point.value - before.value) * fraction;
  }
  return before === null ? null : before.value;
};
var firstBookedHourStartMs = (snapshot) => {
  let earliest = null;
  for (const hour of snapshot.hours) {
    const plannedKWh = Number.isFinite(hour.plannedKWh) ? hour.plannedKWh : 0;
    if (plannedKWh <= 0) continue;
    const coverStartMs = hour.coversFromMs ?? hour.startsAtMs;
    if (earliest === null || coverStartMs < earliest) earliest = coverStartMs;
  }
  return earliest;
};
var resolveStaircaseAnchor = (snapshot, observed, startProgress, windowStartMs) => {
  const firstBookedMs = firstBookedHourStartMs(snapshot);
  if (firstBookedMs === null) return { value: startProgress, atMs: windowStartMs };
  const bracketed = [{ atMs: windowStartMs, value: startProgress }, ...observed];
  const anchorValue = observedValueAt(bracketed, firstBookedMs);
  return anchorValue === null ? { value: startProgress, atMs: windowStartMs } : { value: anchorValue, atMs: firstBookedMs };
};
var buildRevisedStaircase = (snapshot, observed, startProgress, window) => {
  const { windowStartMs, windowEndMs, capValue } = window;
  const revisedAtMs = snapshot.revisedAtMs;
  if (Number.isFinite(revisedAtMs) && revisedAtMs > windowStartMs) {
    const bracketed = [{ atMs: windowStartMs, value: startProgress }, ...observed];
    const anchorValue = observedValueAt(bracketed, revisedAtMs);
    if (anchorValue !== null) {
      return integratePlannedStaircase(snapshot, anchorValue, revisedAtMs, windowEndMs, capValue);
    }
  }
  return integratePlannedStaircase(snapshot, startProgress, windowStartMs, windowEndMs, capValue);
};
var resolveFallbackPrimaryStaircase = (finalPlan, observed, startProgress, window) => {
  if (finalPlan === null) return [];
  const anchor = resolveStaircaseAnchor(finalPlan, observed, startProgress, window.windowStartMs);
  return integratePlannedStaircase(finalPlan, anchor.value, anchor.atMs, window.windowEndMs, window.capValue);
};
var staircasesDiffer = (a, b) => {
  if (a.length !== b.length) return true;
  for (let i = 0; i < a.length; i += 1) {
    if (a[i].atMs !== b[i].atMs) return true;
    if (Math.abs(a[i].value - b[i].value) > 1e-3) return true;
  }
  return false;
};
var finiteOrNull = (raw) => raw === null || !Number.isFinite(raw) ? null : raw;
var pickStartProgress = (entry) => finiteOrNull(
  entry.objectiveKind === "temperature" ? entry.startProgressC : entry.startProgressPercent
);
var pickTargetValue = (entry) => finiteOrNull(
  entry.objectiveKind === "temperature" ? entry.targetTemperatureC : entry.targetPercent
);
var anchorObservedAtStart = (observed, windowStartMs, startProgress) => {
  if (startProgress === null) return [...observed];
  if (observed.length > 0 && observed[0].atMs <= windowStartMs) return [...observed];
  return [{ atMs: windowStartMs, value: startProgress }, ...observed];
};
var pickObservedSamples = (entry) => {
  if (!Array.isArray(entry.progressSamples) || entry.progressSamples.length === 0) {
    return [];
  }
  const out = [];
  for (const sample of entry.progressSamples) {
    if (!Number.isFinite(sample.atMs)) continue;
    const value = entry.objectiveKind === "temperature" ? sample.valueC : sample.valuePercent;
    if (value === null || !Number.isFinite(value)) continue;
    out.push({ atMs: sample.atMs, value });
  }
  return out.sort((a, b) => a.atMs - b.atMs);
};
var hasUsableTrajectory = (observed, originalSnapshotMean, finalSnapshotMean) => {
  if (observed.length >= 2) return true;
  if (typeof originalSnapshotMean === "number" && originalSnapshotMean > 0) return true;
  if (typeof finalSnapshotMean === "number" && finalSnapshotMean > 0) return true;
  return false;
};
var pickMetMarker = (entry) => {
  if (entry.outcome !== "met") return null;
  if (entry.metAtMs === null || !Number.isFinite(entry.metAtMs)) return null;
  return entry.metAtMs;
};
var pickMetMarkerValue = (entry) => {
  if (pickMetMarker(entry) === null) return null;
  if (entry.metReason === "stalled" || entry.metReason === "stalled_device_capped") {
    const finalProgress = entry.objectiveKind === "temperature" ? entry.finalProgressC : entry.finalProgressPercent;
    return Number.isFinite(finalProgress) ? finalProgress : null;
  }
  return pickTargetValue(entry);
};
var buildTrajectoryPayload = (entry, plannedOriginal, plannedFinal, observed, frame) => ({
  mode: "trajectory",
  unit: entry.objectiveKind === "temperature" ? "\xB0C" : "%",
  windowStartMs: frame.windowStartMs,
  windowEndMs: frame.windowEndMs,
  plannedOriginal,
  plannedFinal,
  observed: anchorObservedAtStart(observed, frame.windowStartMs, frame.startProgress),
  target: pickTargetValue(entry),
  metAtMs: pickMetMarker(entry),
  metMarkerValue: pickMetMarkerValue(entry)
});
var composeHeatFromBelowTrajectory = (entry, observed, frame) => {
  const { windowStartMs, windowEndMs, startProgress, target } = frame;
  const plannedOriginal = entry.originalPlan !== null && startProgress !== null ? integratePlannedStaircase(entry.originalPlan, startProgress, windowStartMs, windowEndMs, target) : [];
  const plannedFinalStartAnchored = entry.finalPlan !== null && startProgress !== null ? integratePlannedStaircase(entry.finalPlan, startProgress, windowStartMs, windowEndMs, target) : [];
  const replanned = plannedOriginal.length > 0 && plannedFinalStartAnchored.length > 0 && staircasesDiffer(plannedOriginal, plannedFinalStartAnchored);
  const plannedFinalCandidate = replanned && entry.finalPlan !== null && startProgress !== null ? buildRevisedStaircase(entry.finalPlan, observed, startProgress, { windowStartMs, windowEndMs, capValue: target }) : [];
  const plannedFinal = plannedFinalCandidate.length > 0 ? plannedFinalCandidate : null;
  const fallbackPrimary = startProgress !== null ? resolveFallbackPrimaryStaircase(
    entry.finalPlan,
    observed,
    startProgress,
    { windowStartMs, windowEndMs, capValue: target }
  ) : [];
  const resolvedOriginal = plannedOriginal.length > 0 ? plannedOriginal : fallbackPrimary;
  return buildTrajectoryPayload(entry, resolvedOriginal, plannedFinal, observed, frame);
};
var composeTrajectoryData = (entry, observed, windowStartMs, windowEndMs) => {
  const startProgress = pickStartProgress(entry);
  const target = pickTargetValue(entry);
  const frame = { windowStartMs, windowEndMs, startProgress, target };
  if (startProgress !== null && target !== null && startProgress >= target) {
    const richest = entry.originalPlan ?? entry.finalPlan;
    const primary = resolveFallbackPrimaryStaircase(
      richest,
      observed,
      startProgress,
      { windowStartMs, windowEndMs, capValue: target }
    );
    return buildTrajectoryPayload(entry, primary, null, observed, frame);
  }
  return composeHeatFromBelowTrajectory(entry, observed, frame);
};
var composeLegacyData = (entry, windowStartMs, windowEndMs) => ({
  mode: "legacy_kwh",
  unit: null,
  windowStartMs,
  windowEndMs,
  plannedOriginal: [],
  plannedFinal: null,
  observed: [],
  target: pickTargetValue(entry),
  metAtMs: pickMetMarker(entry),
  metMarkerValue: pickMetMarkerValue(entry)
});
var resolveHistoryDetailChartData = (entry) => {
  const observed = pickObservedSamples(entry);
  const originalMean = entry.originalPlan?.kwhPerUnitMean;
  const finalMean = entry.finalPlan?.kwhPerUnitMean;
  const windowStartMs = entry.startedAtMs;
  const windowEndMs = entry.deadlineAtMs;
  if (!hasUsableTrajectory(observed, originalMean, finalMean)) {
    return composeLegacyData(entry, windowStartMs, windowEndMs);
  }
  const trajectory = composeTrajectoryData(entry, observed, windowStartMs, windowEndMs);
  if (trajectory.plannedOriginal.length === 0 && trajectory.plannedFinal === null && trajectory.observed.length < 2) {
    return composeLegacyData(entry, windowStartMs, windowEndMs);
  }
  return trajectory;
};

// packages/shared-domain/src/deferredActivePlanChartData.ts
var finiteOrNull2 = (raw) => raw === null || raw === void 0 || !Number.isFinite(raw) ? null : raw;
var pickTarget = (plan) => finiteOrNull2(
  plan.objectiveKind === "temperature" ? plan.targetTemperatureC : plan.targetPercent
);
var pickStartProgress2 = (plan) => finiteOrNull2(
  plan.objectiveKind === "temperature" ? plan.startProgressC : plan.startProgressPercent
);
var pickRate = (plan) => {
  const rate = finiteOrNull2(plan.latest?.rateMean ?? plan.kwhPerUnitProvenance?.kWhPerUnit ?? null);
  return rate !== null && rate > 0 ? rate : null;
};
var pickObservedSamples2 = (samples, objectiveKind) => {
  if (!Array.isArray(samples) || samples.length === 0) return [];
  const out = [];
  for (const sample of samples) {
    if (!sample || !Number.isFinite(sample.atMs)) continue;
    const value = objectiveKind === "temperature" ? sample.valueC : sample.valuePercent;
    if (value === null || !Number.isFinite(value)) continue;
    out.push({ atMs: sample.atMs, value });
  }
  return out.sort((a, b) => a.atMs - b.atMs);
};
var emptyChart = (target, windowStartMs, windowEndMs) => ({
  mode: "legacy_kwh",
  unit: null,
  windowStartMs,
  windowEndMs,
  plannedOriginal: [],
  plannedFinal: null,
  observed: [],
  target,
  metAtMs: null,
  metMarkerValue: null
});
var resolveActivePlannedAnchor = (snapshot, withNow, live) => {
  if (live.startProgress !== null) {
    return resolveStaircaseAnchor(snapshot, withNow, live.startProgress, live.windowStartMs);
  }
  if (live.currentValue !== null) {
    return { value: live.currentValue, atMs: live.nowMs ?? live.windowStartMs };
  }
  return null;
};
var resolveActivePlanChartData = (plan, options = {}) => {
  const windowStartMs = plan.startedAtMs;
  const windowEndMs = plan.deadlineAtMs;
  const target = pickTarget(plan);
  const startProgress = pickStartProgress2(plan);
  const samples = pickObservedSamples2(plan.progressSamples, plan.objectiveKind);
  const nowMs = options.nowMs;
  const currentValue = finiteOrNull2(options.currentValue ?? null);
  const withNow = nowMs !== void 0 && currentValue !== null && (samples.length === 0 || samples[samples.length - 1].atMs < nowMs) ? [...samples, { atMs: nowMs, value: currentValue }] : samples;
  const observed = anchorObservedAtStart(withNow, windowStartMs, startProgress);
  const rate = pickRate(plan);
  const latest = plan.latest;
  const snapshot = latest && rate !== null ? { hours: latest.hours, kwhPerUnitMean: rate } : null;
  const anchor = snapshot === null ? null : resolveActivePlannedAnchor(snapshot, withNow, { startProgress, currentValue, windowStartMs, nowMs });
  const planned = snapshot !== null && anchor !== null ? integratePlannedStaircase(snapshot, anchor.value, anchor.atMs, windowEndMs, target) : [];
  if (planned.length === 0 && observed.length < 2) {
    return emptyChart(target, windowStartMs, windowEndMs);
  }
  return {
    mode: "trajectory",
    unit: plan.objectiveKind === "temperature" ? "\xB0C" : "%",
    windowStartMs,
    windowEndMs,
    plannedOriginal: planned,
    plannedFinal: null,
    observed,
    target,
    metAtMs: null,
    metMarkerValue: null
  };
};

// packages/shared-domain/src/deadlineLabels.ts
var PENDING_REASON_MISSING_CAPACITY_COPY = "Learning energy use \u2014 needs power readings from this device.";
var SMART_TASK_LIST_STATUS_LABELS = {
  building_plan: "Building plan\u2026",
  queued: "Scheduled",
  paused_unplugged: "Paused \u2014 unplugged",
  on_track: "On track",
  at_risk: "At risk",
  cannot_meet: "Cannot finish",
  satisfied: "Satisfied"
};
var SMART_TASK_WIDGET_STATUS_LABELS = {
  ...SMART_TASK_LIST_STATUS_LABELS,
  paused_unplugged: "Unplugged"
};
var SMART_TASK_WIDGET_WHY_BY_STATUS = {
  building_plan: null,
  // resolved by pendingReason
  queued: null,
  // composed from firstPlannedTimeLabel when present
  paused_unplugged: "EV is unplugged \u2014 plug in to resume.",
  on_track: null,
  // affirmative line resolved from firstPlannedTimeLabel
  at_risk: null,
  // disambiguated by budget vs time below
  cannot_meet: null,
  // resolved by floor cause / budget bucket count
  satisfied: null
};
var SMART_TASK_WIDGET_WHY_BY_PENDING_REASON = {
  awaiting_horizon_plan: "Waiting for tomorrow\u2019s prices.",
  device_data_missing: "Waiting for a reading from this device.",
  invalid_session: "EV is unplugged \u2014 plug in to start.",
  missing_capacity: "Learning energy use from this device.",
  price_feature_disabled: "Price-aware planning is off."
};
var WHY_CANNOT_MEET_BUDGET = "Today\u2019s daily budget runs out before the deadline.";
var WHY_CANNOT_MEET_DEVICE = "Not enough delivery before the deadline.";
var WHY_AT_RISK_BUDGET = "Today\u2019s daily budget may run out before the deadline.";
var WHY_AT_RISK_TIME = "Limited time left before the deadline.";
var RECOURSE_CANNOT_MEET_BUDGET = "Budget settings show whether future days need power reserved earlier.";
var RECOURSE_CANNOT_MEET_DEVICE = "Device settings show what\u2019s holding it back.";
var RECOURSE_INVALID_SESSION = "Plug the EV in to resume.";
var isBudgetDriven = (input) => {
  if (input.floorShortfallCause !== void 0) return input.floorShortfallCause === "budget";
  return input.statusId === "at_risk" && (input.dailyBudgetExhaustedBucketCount ?? 0) > 0;
};
var resolveSmartTaskWidgetDetailCopy = (input) => {
  if (input.statusId === "cannot_meet") {
    return isBudgetDriven(input) ? { whyLabel: WHY_CANNOT_MEET_BUDGET, recourseHint: RECOURSE_CANNOT_MEET_BUDGET } : { whyLabel: WHY_CANNOT_MEET_DEVICE, recourseHint: RECOURSE_CANNOT_MEET_DEVICE };
  }
  if (input.statusId === "at_risk") {
    return isBudgetDriven(input) ? { whyLabel: WHY_AT_RISK_BUDGET, recourseHint: RECOURSE_CANNOT_MEET_BUDGET } : { whyLabel: WHY_AT_RISK_TIME, recourseHint: null };
  }
  if (input.statusId === "building_plan") {
    const reason = input.pendingReason ?? "awaiting_horizon_plan";
    const why = SMART_TASK_WIDGET_WHY_BY_PENDING_REASON[reason] ?? SMART_TASK_WIDGET_WHY_BY_PENDING_REASON.awaiting_horizon_plan ?? null;
    return {
      whyLabel: why,
      recourseHint: reason === "invalid_session" ? RECOURSE_INVALID_SESSION : null
    };
  }
  if (input.statusId === "queued" && input.firstPlannedTimeLabel) {
    return {
      whyLabel: `Cheaper hours start at ${input.firstPlannedTimeLabel}.`,
      recourseHint: null
    };
  }
  return {
    whyLabel: SMART_TASK_WIDGET_WHY_BY_STATUS[input.statusId],
    recourseHint: null
  };
};
var SMART_TASK_WIDGET_EMPTY_HINT = "Add a smart task from a Flow card for a managed device, or use the New smart task widget to see it here.";
var SMART_TASK_WIDGET_EMPTY_SUBTITLE = "No active smart tasks";
var SMART_TASK_WIDGET_PLAN_META_LABEL_PREFIX = "Estimate";
var CREATE_SMART_TASK_WIDGET_COPY = {
  // Step 1 — device picker.
  pickDeviceTitle: "New smart task",
  pickDevicePrompt: "Choose a device",
  emptyNoDevices: "No eligible devices",
  // Warmer than a bare capability list: name the device kinds AND the next
  // action, so a user with nothing yet knows exactly how to make a device
  // appear here rather than hitting a dead end.
  emptyNoDevicesHint: "Add a thermostat, water heater, or EV charger in Homey and it\u2019ll appear here.",
  loadError: "Could not load devices. Try again later.",
  // Shown while the widget is still wiring up to the Homey app (the SDK bridge
  // hasn't supplied a real API client yet). Distinct from `loadError` (a real
  // fetch that failed): this is a transient "not ready yet" state that resolves
  // on its own once the bridge connects, so it reads as loading rather than a
  // hard failure. The widget never shows canned sample devices on a real boot,
  // and keeps Create disabled until a real client is present, so a user can
  // never see a false "Created" while running against sample data.
  notReady: "Connecting to Homey\u2026",
  // Step 2 — goal + ready-by.
  goalLabel: "Goal",
  readyByLabel: "Ready by",
  previewButton: "Preview",
  // Step 3 — preview + confirm.
  previewTitle: "Preview",
  // Canonical "Scheduled" vocabulary (matches `SMART_TASK_LIST_STATUS_LABELS`
  // / `SMART_TASK_LIST_ROW_LABELS` and the terminology guide) rather than the
  // one-off noun "Runs": the preview's when-window is the same concept the list
  // chip names.
  scheduledLabel: "Scheduled",
  energyLabel: "Energy",
  costLabel: "Cost",
  // The estimate is computed in isolation for this one candidate — surface the
  // caveat honestly rather than implying a guarantee (the
  // `DeferredObjectivePlanPreview` contract documents the same in-isolation
  // direction-of-error). Kept short for the 320–480 px widget.
  estimateCaveat: "Estimate \u2014 the actual run may differ as prices and other tasks change.",
  createButton: "Create smart task",
  backButton: "Back",
  // Shown when the preview can't be projected and the backend did not provide a
  // more specific missing-input reason. Distinct from a hard error. Avoids the
  // reserved "plan" noun (`feedback_terminology_plan_vs_deadline`).
  previewUnavailable: "Can\u2019t preview this yet \u2014 PELS needs more current data for this window.",
  // Shown specifically when the device has no learned energy profile yet
  // (`unavailableReason === 'needs_observation'`): there is no temperature
  // bootstrap rate, so PELS can't estimate the run until it has watched the
  // device draw power. Tells the user the two ways to make that happen rather
  // than (falsely) blaming prices. Names the real per-device toggle
  // ("Power-limit control", see settings-ui `devices.ts`) so the remedy is
  // actionable. Avoids the reserved "plan" noun.
  previewNeedsObservation: "PELS needs to observe this device in action before it can be used for a smart task. Either let it run normally for a while, or turn on Power-limit control for it.",
  // Shown when the candidate's goal is already met (preview `status: 'satisfied'`
  // → zero scheduled hours): there is nothing to schedule, so explain that
  // honestly rather than reusing the no-prices line. Uses the canonical "goal"
  // noun (matches `goalLabel`) and avoids the reserved "plan" noun.
  previewSatisfied: "This goal is already met \u2014 nothing to schedule.",
  // Pending state on the Create button while the /create round-trip is in
  // flight. Distinct from `created` (the confirmed-success label): the button
  // must read as work-in-progress, never as success, until a `{ ok: true }`
  // create actually lands — otherwise a still-pending or later-failed create
  // would have flashed "Smart task created" before anything was persisted.
  creating: "Creating\u2026",
  // Shown briefly after a successful create before the widget resets.
  created: "Smart task created",
  // Generic submit failure (rejected candidate / transient SDK miss).
  createError: "Could not create the smart task. Check the goal and try again.",
  // A transient settings-write refusal (`write_conflict`): the goal was valid,
  // the persist just flaked, so the data is safe and a plain retry resolves it.
  // Distinct from `createError` so we never tell the user to "check the goal"
  // for a failure that has nothing to do with their input.
  writeConflict: "Could not save the smart task just now. Try again.",
  // The previewed "Ready by" time slipped into the past between previewing and
  // confirming (the user lingered past the chosen minute). The create is
  // rejected rather than silently rolled to the next day so the created task
  // can never disagree with the window the preview promised — re-previewing
  // resolves a fresh future deadline. Retryable, not a hard failure.
  deadlinePassed: "That ready-by time just passed. Preview again to pick a fresh time.",
  // Step 2 — optional "Extra permissions" disclosure. Collapsed and OFF by
  // default; a user opts in per task. The section hint stays honest about scope
  // (only to hit THIS deadline) and never implies more total power or a raised
  // cap (`feedback_hard_cap_is_physical`). The two toggle labels themselves come
  // from `SMART_TASK_EXTRA_PERMISSION_LABELS` so the widget, the settings-UI
  // breadcrumb, and runtime logs all read identically.
  extraPermissionsTitle: "Extra permissions",
  extraPermissionsHint: "Off unless you turn them on \u2014 only used to hit this deadline.",
  // Shown under the limit-lower-priority toggle when it is disabled: that
  // permission only has any effect alongside the budget one, so it is gated on it.
  limitLowerPriorityNeedsBudget: "Turn on \u201CMay go over daily budget\u201D to use this.",
  // Shown in the preview when the in-isolation projection returns a real planner
  // verdict that the deadline may not be met — `cannot_meet` (won't make it) or
  // `at_risk` (might not). Surfaced as a prominent warning so a user never
  // commits an unreachable ready-by believing it is fine. The estimate
  // UNDERSTATES this risk (it projects the candidate in isolation — see the
  // `DeferredObjectivePlanPreview` contract), so the copy is a plain warning, not
  // a soft hint. Distinct from `previewUnavailable`, which is a missing-price /
  // projection gap rather than a feasibility verdict.
  cannotMeet: "Cannot finish \u2014 not enough usable time before this ready-by time.",
  atRisk: "At risk \u2014 this may need most of the available window."
};
var PREVIEW_UNAVAILABLE_COPY_BY_REASON = {
  invalid_deadline: "Can\u2019t preview this ready-by time yet.",
  invalid_session: "Can\u2019t preview this yet \u2014 plug the EV in to start.",
  missing_capacity: "Can\u2019t preview this yet \u2014 PELS needs power readings from this device.",
  missing_device: "Can\u2019t preview this yet \u2014 PELS can\u2019t find this device.",
  needs_observation: CREATE_SMART_TASK_WIDGET_COPY.previewNeedsObservation,
  missing_prices: "Can\u2019t preview this yet \u2014 prices through this window are not available yet.",
  missing_reading: "Can\u2019t preview this yet \u2014 PELS needs a current device reading.",
  price_feature_disabled: "Can\u2019t preview this yet \u2014 price-aware planning is off.",
  progress_stale: "Can\u2019t preview this yet \u2014 PELS needs a fresher device reading.",
  unknown: CREATE_SMART_TASK_WIDGET_COPY.previewUnavailable
};
var resolveBuildingPlanChipTone = () => "info";
var resolvePausedUnpluggedChipTone = () => "warn";
var SMART_TASK_LIST_STATUS_CHIP_VARIANT = {
  building_plan: resolveBuildingPlanChipTone(),
  queued: "muted",
  paused_unplugged: resolvePausedUnpluggedChipTone(),
  on_track: "ok",
  at_risk: "warn",
  cannot_meet: "alert",
  satisfied: "ok"
};
var SMART_TASK_LIST_READY_BY_STATUS_WORD = {
  building_plan: null,
  queued: null,
  // The inline word is joined to the timestamp with an em-dash separator
  // ("Ready by … — <word>"). For paused we use the compressed widget label
  // ('Unplugged') rather than the full chip label ('Paused — unplugged'): the
  // latter carries its own em-dash, which would render a confusing double-dash
  // ("… — Paused — unplugged") on the Ready-by line. The chip still shows the
  // full label; this is the same sanctioned shared-domain string, not a new
  // variant.
  paused_unplugged: SMART_TASK_WIDGET_STATUS_LABELS.paused_unplugged,
  on_track: null,
  at_risk: SMART_TASK_LIST_STATUS_LABELS.at_risk,
  cannot_meet: SMART_TASK_LIST_STATUS_LABELS.cannot_meet,
  satisfied: null
};
var formatConfidenceChipLabel = (confidence) => {
  if (confidence === "low") return "Estimating";
  if (confidence === "medium") return "Refining";
  return null;
};
var MIN_LEARNED_SAMPLES_FOR_CONFIDENT_CHIP = 4;
var resolveSmartTaskLearning = (provenance) => {
  if (!provenance) return false;
  if (provenance.source === "bootstrap") return true;
  return provenance.acceptedSamples < MIN_LEARNED_SAMPLES_FOR_CONFIDENT_CHIP;
};
var formatSmartTaskListConfidenceChipLabel = (params) => {
  if (params.statusId === "cannot_meet" || params.statusId === "on_track") return null;
  if (!params.learning) return null;
  return formatConfidenceChipLabel(params.confidence);
};
var SMART_TASK_LIST_ROW_LABELS = {
  target: "Target",
  starts: "Starts",
  readyBy: "Ready by"
};
var SMART_TASK_WIDGET_DUE_VERB = "Due";
var resolveSmartTaskWidgetEtaVerb = (isFailing) => isFailing ? SMART_TASK_WIDGET_DUE_VERB : SMART_TASK_LIST_ROW_LABELS.readyBy;
var SMART_TASK_WIDGET_TARGET_ACTION_VERB = {
  temperature: "Heat to",
  ev_soc: "Charge to"
};
var resolveSmartTaskWidgetTargetActionVerb = (kind) => SMART_TASK_WIDGET_TARGET_ACTION_VERB[kind];
var SMART_TASK_WIDGET_TARGET_NOUN = SMART_TASK_LIST_ROW_LABELS.target;
var resolveSmartTaskListStatus = (params) => {
  const { pending, pendingReason, diagnosticReasonCode, planStatus, firstActionAtMs, nowMs } = params;
  if (diagnosticReasonCode === "objective_invalid_session") return "paused_unplugged";
  if (pending || planStatus === void 0) {
    if (pendingReason === "invalid_session") return "paused_unplugged";
    return "building_plan";
  }
  if (firstActionAtMs !== null && firstActionAtMs > nowMs) return "queued";
  if (planStatus === "satisfied") return "satisfied";
  if (planStatus === "cannot_meet") return "cannot_meet";
  if (planStatus === "at_risk") return "at_risk";
  return "on_track";
};
var REVISION_REASON_TOOLTIP_LINE = {
  flow_card: "Updated after a flow card fired",
  prices_arrived: "Updated as prices became available",
  objective_changed: "Updated after the target changed",
  // Only fires when the planner consumed a newer price horizon than the
  // previous revision. `schedule_revised` carries internal replans.
  prices_revised: "Updated as new prices arrived",
  // Schedule shifted without a new price horizon — daily-budget pressure
  // moved a bucket, planStatus flipped, etc. Honest about the cause without
  // claiming a publication event.
  schedule_revised: "Updated as the schedule was revised",
  rate_refined: "Updated as rates were refined",
  flow_permission_changed: "Updated after a Flow changed what this smart task may do"
};
var SCHEDULE_REVISED_BASE = "Schedule revised";
var SCHEDULE_REVISED_BUDGET = `${SCHEDULE_REVISED_BASE} \u2014 daily budget shifted`;
var SCHEDULE_REVISED_RISK = `${SCHEDULE_REVISED_BASE} \u2014 risk changed`;
var SCHEDULE_REVISED_OPENED = `${SCHEDULE_REVISED_BASE} \u2014 cheaper hour opened`;
var withLastFetched = (base, lastFetchedShort) => lastFetchedShort ? `${base} Last price update: ${lastFetchedShort}.` : base;
var resolveQueuedHeadlineReason = (params) => {
  if (params.pricesShortOfDeadline) {
    return `Waiting for tomorrow\u2019s prices through ${params.deadlineTime}.`;
  }
  if (params.dailyBudgetExhausted) {
    return "Today\u2019s budget is full \u2014 next cheap window after midnight.";
  }
  return `Cheaper than now \u2014 starts at ${params.firstPlannedTime}.`;
};
var CANNOT_MEET_RECOURSE = {
  openBudget: { label: "Open Budget", targetTab: "budget" },
  openOverview: { label: "Adjust device", targetTab: "overview" }
};
var OVERVIEW_DEVICE_RECOURSE_BASE = { label: "Open device in Overview", targetTab: "overview" };
var overviewDeviceRecourse = (deviceId) => ({ ...OVERVIEW_DEVICE_RECOURSE_BASE, deviceId });
var awaitingHorizonCopy = (kindNoun) => ((ctx) => {
  const isFlow = ctx.priceSource === "external_flow";
  const body = isFlow ? `PELS needs prices through the deadline before it can build a ${kindNoun}. In flow price mode, prices arrive only when a Flow calls the \u201CSet external prices (tomorrow)\u201D action. Check the Flow that publishes prices if this message stays up after tomorrow\u2019s prices should have arrived.` : `PELS will build a ${kindNoun} as soon as prices through the deadline are available.`;
  return {
    headline: isFlow ? "Waiting for tomorrow\u2019s prices from your Flow" : "Waiting for tomorrow\u2019s prices",
    body: withLastFetched(body, ctx.lastFetchedShort),
    // Avoid restating "Waiting for tomorrow’s prices" from the headline; the
    // panic-visitor's actionable detail is the horizon time the planner
    // needs to cover.
    headlineReason: `Need prices through ${ctx.deadlineTime} before the smart task can start.`,
    recourse: null
  };
});
var deviceDataMissingResolver = (kind) => (ctx) => ({
  headline: kind.headline,
  body: kind.body,
  headlineReason: `PELS can\u2019t read the ${kind.readingNoun} from ${ctx.deviceName.trim() || kind.fallbackDeviceNoun}.`,
  recourse: overviewDeviceRecourse(ctx.deviceId)
});
var [MISSING_CAPACITY_HEADLINE, MISSING_CAPACITY_BODY_FRAGMENT] = PENDING_REASON_MISSING_CAPACITY_COPY.split(" \u2014 ");
var MISSING_CAPACITY_BODY = `${MISSING_CAPACITY_BODY_FRAGMENT[0].toUpperCase()}${MISSING_CAPACITY_BODY_FRAGMENT.slice(1)}`;
var HEATER_DEVICE_DATA_MISSING = deviceDataMissingResolver({
  headline: "Waiting for a reading from the device",
  body: "PELS needs a current temperature, a useful capacity, or a recent observation from this heater before it can plan the smart task.",
  readingNoun: "current temperature",
  fallbackDeviceNoun: "the heater"
});
var EV_DEVICE_DATA_MISSING = deviceDataMissingResolver({
  headline: "Waiting for a reading from the EV",
  body: "PELS needs a current state of charge, a charge rate, or a recent observation from this EV before it can plan the smart task.",
  readingNoun: "state of charge",
  fallbackDeviceNoun: "the EV"
});
var DEADLINE_LABELS = {
  temperature: {
    kindChipLabel: "Temperature",
    activeChipLabel: "Heating",
    sectionLabel: "Heating smart task",
    liveStateChipLabel: {
      active: "Heating",
      building_plan: "Building plan\u2026",
      queued: "Scheduled",
      // Thermal devices can't be unplugged; the variant is unreachable here
      // and falls back to the generic scheduled copy if the resolver ever
      // hands a stale value through.
      paused_unplugged: "Scheduled",
      ok: "On track"
    },
    atRiskChipLabel: SMART_TASK_LIST_STATUS_LABELS.at_risk,
    cannotMeetChipLabel: "Cannot finish",
    deviceSeriesName: "Heating",
    originalDeviceSeriesName: "Original Heating",
    actualDeviceSeriesName: "Measured Heating",
    backgroundSeriesName: "Background usage",
    progressSeriesName: "Temperature",
    planTooltipIdle: "Idle",
    // Thermal `invalid_session` is unreachable today (heaters can't be
    // unplugged); we map it to `device_data_missing` so a future diagnostic
    // can't leak EV-specific copy. `missing_capacity` is the cold-start
    // "learning energy profile" state — no shipped bootstrap kWh/°C — and
    // recourse lands on Overview where the user can verify the heater is
    // actually running and reporting power.
    pendingHeroByReason: {
      awaiting_horizon_plan: awaitingHorizonCopy("heat plan"),
      price_feature_disabled: () => ({
        headline: "Price-aware optimisation is off",
        body: "Enable price-aware optimisation in Settings \u2192 Electricity prices to compute a heat plan.",
        headlineReason: "Price-aware optimisation is off in Settings.",
        recourse: { label: "Open Settings", targetTab: "settings" }
      }),
      device_data_missing: HEATER_DEVICE_DATA_MISSING,
      invalid_session: HEATER_DEVICE_DATA_MISSING,
      // Cold-start `missing_capacity` collapses to a single user-facing line —
      // headline + metaLine combined parse as `PENDING_REASON_MISSING_CAPACITY_COPY`
      // ("Learning energy use — needs power readings from this device."). Earlier
      // copy split the explanation across body + headlineReason, which buried the
      // "give it power readings" lever in a paragraph. The pending-reason path
      // here intentionally addresses only `objective_missing_capacity`
      // (no-profile cold-start); the thermal `objective_missing_charge_rate`
      // fall-through still routes to this resolver via `THERMAL_LEARNING_CAPACITY_REASON_CODES`
      // in the recorder, which is the same "still learning" user state from
      // their point of view.
      missing_capacity: (ctx) => ({
        headline: MISSING_CAPACITY_HEADLINE,
        body: MISSING_CAPACITY_BODY,
        headlineReason: null,
        recourse: overviewDeviceRecourse(ctx.deviceId)
      })
    },
    unavailableByReason: {
      no_current_reading: {
        headline: "Waiting for the first temperature reading",
        body: "The schedule will appear once the device reports its current temperature."
      },
      already_satisfied: {
        headline: "Satisfied",
        body: "The current temperature already meets the smart task target. PELS will schedule it again if the temperature drops below target."
      }
    },
    // Drops the raw progress-unit delta ("Short by about 41.9 °C") that users
    // misread as a wild temperature anomaly. The underlying shortfall is energy
    // / time against the plan, not a raw temperature gap; the chip + headline
    // already say the verdict ("Cannot finish"); body states the cause and the
    // user-side levers. The hero meta line follows with the "Needs N kWh · Y
    // hours left · …" line via `formatMetaLine`, which is the right surface for
    // magnitude. Recourse copy names the two levers that aren't the daily
    // budget; the budget remedy is handled by the dedicated
    // `cannotMeetDailyBudgetExhausted` branch above.
    cannotMeetShortfall: () => "Not enough time for this target. Lower the target or move the deadline.",
    cannotMeetDailyBudgetExhausted: "Today's daily budget is fully booked. Lower it so future days reserve power earlier, or move the deadline.",
    cannotMeetRecourse: CANNOT_MEET_RECOURSE,
    resolveQueuedHeadlineReason,
    completedHero: {
      headline: "Smart task finished",
      body: "See Smart tasks for the outcome."
    },
    targetUnit: "\xB0C",
    planInputsCardTitle: "What PELS has learned",
    planInputsRateRowLabel: "Energy needed per \xB0C",
    planInputsMaxPowerRowLabel: "Device power used",
    perUnitRateUnit: "kWh/\xB0C",
    planInputsRateBootstrapNote: null,
    revisionReasonTooltipLine: REVISION_REASON_TOOLTIP_LINE
  },
  ev_soc: {
    kindChipLabel: "EV",
    activeChipLabel: "Charging",
    sectionLabel: "EV smart task",
    liveStateChipLabel: {
      active: "Charging",
      building_plan: "Building plan\u2026",
      queued: "Scheduled",
      paused_unplugged: "Paused \u2014 unplugged",
      ok: "On track"
    },
    atRiskChipLabel: SMART_TASK_LIST_STATUS_LABELS.at_risk,
    cannotMeetChipLabel: "Cannot finish",
    deviceSeriesName: "Charging",
    originalDeviceSeriesName: "Original Charging",
    actualDeviceSeriesName: "Measured Charging",
    backgroundSeriesName: "Background usage",
    progressSeriesName: "Charge level",
    planTooltipIdle: "Idle",
    // EV `invalid_session` is the plugged-out / discharging pause state. The
    // body already says "PELS will resume…", the headlineReason restates the
    // *cause* at headline height, and recourse is null because plugging in
    // is a physical action with no in-app tab to land on. EV
    // `missing_capacity` should never fire (bootstrap fallback exists); the
    // device-data-missing copy is kept as a safety net.
    pendingHeroByReason: {
      awaiting_horizon_plan: awaitingHorizonCopy("charging plan"),
      price_feature_disabled: () => ({
        headline: "Price-aware optimisation is off",
        body: "Enable price-aware optimisation in Settings \u2192 Electricity prices to compute a charging plan.",
        headlineReason: "Price-aware optimisation is off in Settings.",
        recourse: { label: "Open Settings", targetTab: "settings" }
      }),
      device_data_missing: EV_DEVICE_DATA_MISSING,
      invalid_session: () => ({
        headline: "Charging paused \u2014 EV unplugged",
        body: "PELS will resume the schedule once the EV is plugged in and reports a valid charging session.",
        headlineReason: "Charger reports the car isn\u2019t plugged in.",
        recourse: null
      }),
      missing_capacity: EV_DEVICE_DATA_MISSING
    },
    unavailableByReason: {
      no_current_reading: {
        headline: "Waiting for the first state-of-charge reading",
        body: "The schedule will appear once the EV reports its current state of charge."
      },
      already_satisfied: {
        headline: "Satisfied",
        body: "The EV is already at or above the smart task target. PELS will schedule it again if the state of charge drops below target."
      }
    },
    // EV mirrors the thermal copy: drop the raw % shortfall figure (users can
    // read it as "the car lost 30 % of charge") in favour of plain-language
    // recourse. The meta line continues to carry the energy/duration magnitude.
    cannotMeetShortfall: () => "Not enough time or charging power for this target. Lower the target or move the deadline.",
    cannotMeetDailyBudgetExhausted: "Today's daily budget is fully booked. Lower it so future days reserve power earlier, or move the deadline.",
    cannotMeetRecourse: CANNOT_MEET_RECOURSE,
    resolveQueuedHeadlineReason,
    completedHero: {
      headline: "Smart task finished",
      body: "See Smart tasks for the outcome."
    },
    targetUnit: "%",
    planInputsCardTitle: "What PELS has learned",
    planInputsRateRowLabel: "Energy needed per %",
    planInputsMaxPowerRowLabel: "Device power used",
    perUnitRateUnit: "kWh/%",
    planInputsRateBootstrapNote: "Estimated \u2014 refining as PELS observes charging.",
    revisionReasonTooltipLine: REVISION_REASON_TOOLTIP_LINE
  }
};
var EV_CARD_HOUR_MS = 60 * 60 * 1e3;
var SAMPLE_STALE_THRESHOLD_MS = 24 * 60 * 60 * 1e3;
var ONE_MINUTE_MS = 60 * 1e3;
var ONE_HOUR_MS = 60 * ONE_MINUTE_MS;

// packages/shared-domain/src/deferredPlanHistoryAttribution.ts
var DELIVERED_PLAN_FRACTION = 0.95;
var NO_DELIVERY_KWH_FLOOR = 0.1;
var NO_DELIVERY_PROGRESS_DEADBAND_C = 0.5;
var NO_DELIVERY_PROGRESS_DEADBAND_PERCENT = 1;
var sumPlannedKWh = (snapshot) => {
  let total = 0;
  for (const hour of snapshot.hours) {
    if (Number.isFinite(hour.plannedKWh) && hour.plannedKWh > 0) total += hour.plannedKWh;
  }
  return total;
};
var pickSnapshot = (entry) => entry.finalPlan ?? entry.originalPlan ?? null;
var resolveProgressTowardTarget = (entry) => {
  if (entry.objectiveKind === "temperature") {
    const start2 = entry.startProgressC;
    const final2 = entry.finalProgressC;
    if (!Number.isFinite(start2) || !Number.isFinite(final2)) return null;
    return { delta: final2 - start2, deadband: NO_DELIVERY_PROGRESS_DEADBAND_C };
  }
  const start = entry.startProgressPercent;
  const final = entry.finalProgressPercent;
  if (!Number.isFinite(start) || !Number.isFinite(final)) return null;
  return { delta: final - start, deadband: NO_DELIVERY_PROGRESS_DEADBAND_PERCENT };
};
var resolveNoDelivery = (entry, deliveredKWh) => {
  const progress = resolveProgressTowardTarget(entry);
  if (progress === null) return false;
  if (progress.delta >= progress.deadband) return false;
  if (deliveredKWh === null) return true;
  return deliveredKWh < NO_DELIVERY_KWH_FLOOR;
};
var resolveCause = (params) => {
  const { outcome, snapshot, deliveredAtOrAbovePlan, noDelivery } = params;
  if (outcome !== "missed") return null;
  if (snapshot !== null && (snapshot.dailyBudgetExhaustedBucketCount ?? 0) > 0) {
    return "budget_limited";
  }
  if (noDelivery) return "no_delivery";
  if (snapshot === null) return "unknown";
  if (deliveredAtOrAbovePlan === false) return "capacity_shortfall";
  if (deliveredAtOrAbovePlan === true) return "energy_underestimate";
  if (typeof snapshot.acceptedSamples === "number" && snapshot.acceptedSamples < MIN_LEARNED_SAMPLES_FOR_CONFIDENT_CHIP) {
    return "low_confidence";
  }
  return "unknown";
};
var resolveDeliveredKWh = (entry) => typeof entry.deliveredKWh === "number" && Number.isFinite(entry.deliveredKWh) ? entry.deliveredKWh : null;
var normalizeEnergyExpectedKWh = (value) => {
  if (typeof value !== "number" || !Number.isFinite(value) || value <= 0) return null;
  return value;
};
var pickResolvedMean = (snapshot, hint) => normalizeEnergyExpectedKWh(snapshot?.energyExpectedKWh) ?? normalizeEnergyExpectedKWh(hint);
var resolveDeliveredAtOrAbovePlan = (deliveredKWh, plannedKWh, energyExpectedKWh) => {
  const comparisonBasis = energyExpectedKWh ?? plannedKWh;
  if (deliveredKWh === null || comparisonBasis === null || comparisonBasis <= 0) return null;
  return deliveredKWh >= comparisonBasis * DELIVERED_PLAN_FRACTION;
};
var resolveDeferredPlanHistoryMissAttribution = (entry, energyExpectedKWh = null) => {
  const snapshot = pickSnapshot(entry);
  const plannedTotal = snapshot === null ? null : sumPlannedKWh(snapshot);
  const plannedKWh = plannedTotal !== null && plannedTotal > 0 ? plannedTotal : null;
  const deliveredKWh = resolveDeliveredKWh(entry);
  const deliveredAtOrAbovePlan = resolveDeliveredAtOrAbovePlan(
    deliveredKWh,
    plannedKWh,
    pickResolvedMean(snapshot, energyExpectedKWh)
  );
  return {
    cause: resolveCause({
      outcome: entry.outcome,
      snapshot,
      deliveredAtOrAbovePlan,
      noDelivery: resolveNoDelivery(entry, deliveredKWh)
    }),
    plannedKWh,
    deliveredKWh,
    planningSpeedKw: snapshot?.planningSpeedKw ?? null,
    rateConfidence: snapshot?.rateConfidence ?? null,
    acceptedSamples: snapshot?.acceptedSamples ?? null,
    dailyBudgetExhaustedBucketCount: snapshot?.dailyBudgetExhaustedBucketCount ?? 0,
    deliveredAtOrAbovePlan
  };
};
var STILL_LEARNING_CAUSE = "Still learning this device's energy use.";
var formatRefinedMissCause = (entry) => {
  const attribution = resolveDeferredPlanHistoryMissAttribution(entry);
  switch (attribution.cause) {
    case "no_delivery":
      return entry.objectiveKind === "temperature" ? "Delivered almost no heat before the deadline." : "Delivered almost no charge before the deadline.";
    case "energy_underestimate":
      return "Target needed more energy than estimated.";
    case "low_confidence":
      return STILL_LEARNING_CAUSE;
    default:
      return null;
  }
};

// packages/shared-domain/src/utils/dateUtils.ts
var DAY_START_SEARCH_WINDOW_MS = 72 * 60 * 60 * 1e3;
function formatTimeInTimeZone(date, options, timeZone) {
  return date.toLocaleTimeString([], { timeZone, ...options });
}

// packages/shared-domain/src/deferredPlanHistoryHourlyStrip.ts
var HOUR_MS2 = 60 * 60 * 1e3;

// packages/shared-domain/src/deferredPlanHistory.ts
var formatTemperature = (value) => value === null ? null : `${value.toFixed(1)} \xB0C`;
var formatPercent = (value) => value === null ? null : `${value.toFixed(0)} %`;
var resolveDisplayedEndValue = (outcome, metReason, finalValue, targetValue) => outcome === "met" && metReason === void 0 && finalValue !== null && targetValue !== null && finalValue < targetValue ? targetValue : finalValue;
var formatPlanHistoryProgressLine = (entry) => {
  const suppressArrow = entry.outcome === "abandoned" || entry.outcome === "replaced";
  if (entry.objectiveKind === "temperature") {
    const start2 = formatTemperature(entry.startProgressC);
    const target2 = formatTemperature(entry.targetTemperatureC);
    if (!start2 || !target2) return null;
    if (suppressArrow) return `${start2}  \xB7  target ${target2}`;
    const endC = resolveDisplayedEndValue(
      entry.outcome,
      entry.metReason,
      entry.finalProgressC,
      entry.targetTemperatureC
    );
    const end2 = formatTemperature(endC);
    return `${start2} \u2192 ${end2 ?? "\u2014"}  \xB7  target ${target2}`;
  }
  const start = formatPercent(entry.startProgressPercent);
  const target = formatPercent(entry.targetPercent);
  if (!start || !target) return null;
  if (suppressArrow) return `${start}  \xB7  target ${target}`;
  const endPct = resolveDisplayedEndValue(
    entry.outcome,
    entry.metReason,
    entry.finalProgressPercent,
    entry.targetPercent
  );
  const end = formatPercent(endPct);
  return `${start} \u2192 ${end ?? "\u2014"}  \xB7  target ${target}`;
};
var formatPlanHistoryReachedAtLine = (entry, timeZone = "UTC") => {
  if (entry.outcome !== "met" || entry.metAtMs === null) return null;
  const date = new Date(entry.metAtMs);
  if (Number.isNaN(date.getTime())) return null;
  const timeLabel = formatTimeInTimeZone(
    date,
    { hour: "2-digit", minute: "2-digit", hourCycle: "h23" },
    timeZone
  );
  return `reached at ${timeLabel}`;
};
var OUTCOME_LABELS = {
  met: "Succeeded",
  missed: "Missed",
  abandoned: "Abandoned",
  replaced: "Abandoned",
  unknown: "Unknown"
};
var OUTCOME_TONES = {
  met: "ok",
  missed: "warn",
  abandoned: "muted",
  replaced: "muted",
  unknown: "muted"
};
var getPlanHistoryOutcomeLabel = (outcome) => OUTCOME_LABELS[outcome];
var getPlanHistoryOutcomeTone = (outcome) => OUTCOME_TONES[outcome];
var MINUTE_MS = 60 * 1e3;
var HOUR_MS3 = 60 * MINUTE_MS;
var snapshotShowsBudgetExhausted = (snapshot) => snapshot !== null && typeof snapshot.dailyBudgetExhaustedBucketCount === "number" && snapshot.dailyBudgetExhaustedBucketCount > 0;
var pickLastPlan = (entry) => (
  // Prefer the final plan's status — it reflects the planner's last word
  // before finalization. Fall back to the original snapshot when the run
  // finalized before the planner replanned (no finalPlan recorded).
  entry.finalPlan ?? entry.originalPlan
);
var formatPlanHistoryMissedReason = (entry) => {
  if (entry.outcome !== "missed") return null;
  const lastPlan = pickLastPlan(entry);
  if (snapshotShowsBudgetExhausted(lastPlan)) {
    return "Daily budget filled before the deadline.";
  }
  const refinedCause = formatRefinedMissCause(entry);
  if (refinedCause !== null) return refinedCause;
  if (lastPlan?.planStatus === "cannot_meet") {
    return "Couldn't reserve enough cheap hours in time.";
  }
  if (lastPlan?.planStatus === "at_risk") {
    return "Fell behind and didn't catch up in time.";
  }
  if (entry.discoveredFrom === "backfill") {
    return "PELS restarted mid-task; outcome estimated.";
  }
  return "Didn't reach the target before the deadline.";
};

// widgets/smart_tasks/src/smartTasksWidgetPayload.ts
var ROW_CAP = 3;
var ENDED_ROW_CAP = 5;
var ENDED_WINDOW_MS = 24 * 60 * 60 * 1e3;
var EMPTY_SUBTITLE_DEFAULT = SMART_TASK_WIDGET_EMPTY_SUBTITLE;
var STATUS_TIER = {
  cannot_meet: 0,
  at_risk: 1,
  paused_unplugged: 2,
  building_plan: 2,
  queued: 3,
  on_track: 3,
  satisfied: 99
};
var STATUS_TONE = {
  cannot_meet: "danger",
  at_risk: "warn",
  paused_unplugged: "muted",
  building_plan: "muted",
  queued: "ok",
  on_track: "ok",
  satisfied: "ok"
};
var isFiniteNumber = (value) => typeof value === "number" && Number.isFinite(value);
var toWidgetChart = (chart) => chart.mode === "trajectory" ? chart : null;
var resolveCurrentValue = (device, kind) => {
  if (!device) return null;
  if (kind === "temperature") {
    return isFiniteNumber(device.currentTemperature) ? device.currentTemperature : null;
  }
  const percent = device.stateOfCharge?.percent;
  return isFiniteNumber(percent) ? percent : null;
};
var resolveTargetValue = (plan) => {
  if (plan.objectiveKind === "temperature") {
    return isFiniteNumber(plan.targetTemperatureC) ? plan.targetTemperatureC : null;
  }
  return isFiniteNumber(plan.targetPercent) ? plan.targetPercent : null;
};
var resolvePlannerEtaMs = (plan) => {
  const hours = plan.latest?.hours;
  if (!hours || hours.length === 0) return null;
  const last = hours[hours.length - 1];
  return isFiniteNumber(last.startsAtMs) ? last.startsAtMs + 60 * 60 * 1e3 : null;
};
var formatLocalHHMMFallback = (date) => `${String(date.getHours()).padStart(2, "0")}:${String(date.getMinutes()).padStart(2, "0")}`;
var formatLocalHHMM = (ms, timeZone) => {
  const date = new Date(ms);
  if (!Number.isFinite(date.getTime())) return "";
  try {
    return new Intl.DateTimeFormat("en-GB", {
      hour: "2-digit",
      minute: "2-digit",
      hour12: false,
      timeZone: timeZone ?? void 0
    }).format(date);
  } catch {
    return formatLocalHHMMFallback(date);
  }
};
var calendarDayIndex = (ms, timeZone) => {
  try {
    const ymd = new Intl.DateTimeFormat("en-CA", {
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
      timeZone: timeZone ?? void 0
    }).format(new Date(ms));
    const [y, m, d] = ymd.split("-").map(Number);
    return Math.round(Date.UTC(y, m - 1, d) / (24 * 60 * 60 * 1e3));
  } catch {
    const date = new Date(ms);
    return Math.round(
      Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()) / (24 * 60 * 60 * 1e3)
    );
  }
};
var localDayDiff = (deadlineMs, nowMs, timeZone) => calendarDayIndex(deadlineMs, timeZone) - calendarDayIndex(nowMs, timeZone);
var formatDeadlineLong = (ms, nowMs, timeZone) => {
  const date = new Date(ms);
  if (!Number.isFinite(date.getTime())) return "";
  const timePart = formatLocalHHMM(ms, timeZone);
  const dayDiff = localDayDiff(ms, nowMs, timeZone);
  if (dayDiff === 0) return `Today ${timePart}`;
  if (dayDiff === 1) return `Tomorrow ${timePart}`;
  try {
    if (dayDiff >= -6 && dayDiff <= 6) {
      const weekday = new Intl.DateTimeFormat("en-GB", {
        weekday: "short",
        timeZone: timeZone ?? void 0
      }).format(date);
      return `${weekday} ${timePart}`;
    }
    const dayMonth = new Intl.DateTimeFormat("en-GB", {
      day: "numeric",
      month: "short",
      timeZone: timeZone ?? void 0
    }).format(date);
    return `${dayMonth} ${timePart}`;
  } catch {
    return formatLocalHHMMFallback(date);
  }
};
var formatDurationFromHours = (hours) => {
  if (!Number.isFinite(hours) || hours <= 0) return "";
  const totalMinutes = Math.max(1, Math.round(hours * 60));
  const h = Math.floor(totalMinutes / 60);
  const m = totalMinutes % 60;
  if (h === 0) return `${m}m`;
  if (m === 0) return `${h}h`;
  return `${h}h ${m}m`;
};
var formatKwh = (value) => {
  if (!Number.isFinite(value) || value <= 0) return "";
  const rounded = Math.round(value * 10) / 10;
  return `${rounded.toFixed(1)} kWh`;
};
var resolveDurationPart = (revision) => {
  if (revision.estimatedDurationText) return `\u2248${revision.estimatedDurationText}`;
  const speed = revision.planningSpeedKw;
  if (speed && speed > 0 && revision.energyNeededKWh > 0) {
    const dur = formatDurationFromHours(revision.energyNeededKWh / speed);
    return dur ? `\u2248${dur}` : null;
  }
  return null;
};
var resolveSpeedPart = (revision) => {
  const speed = revision.planningSpeedKw;
  if (!speed || speed <= 0) return null;
  return `${(Math.round(speed * 10) / 10).toFixed(1)} kW`;
};
var resolveEnergyPart = (revision) => {
  const expected = revision.energyExpectedKWh;
  const needed = revision.energyNeededKWh;
  if (isFiniteNumber(expected) && expected > 0 && needed > 0 && Math.abs(expected - needed) > 0.05) {
    const low = Math.round(Math.min(expected, needed) * 10) / 10;
    const high = Math.round(Math.max(expected, needed) * 10) / 10;
    return `\u2248${low.toFixed(1)}\u2013${high.toFixed(1)} kWh`;
  }
  if (needed > 0) return `\u2248${formatKwh(needed)}`;
  return null;
};
var formatPlanMetaLabel = (revision) => {
  const parts = [
    resolveDurationPart(revision),
    resolveSpeedPart(revision),
    resolveEnergyPart(revision)
  ].filter((part) => part !== null && part !== "");
  if (parts.length === 0) return null;
  return `${SMART_TASK_WIDGET_PLAN_META_LABEL_PREFIX} ${parts.join(" \xB7 ")}`;
};
var resolveConfidenceLabel = (provenance, statusId) => formatSmartTaskListConfidenceChipLabel({
  confidence: provenance?.displayConfidence ?? provenance?.confidence ?? null,
  statusId,
  learning: resolveSmartTaskLearning(provenance)
});
var emptyPayload = (subtitle, hint) => ({
  state: "empty",
  subtitle,
  hint
});
var compareCandidates = (a, b) => {
  if (a.tier !== b.tier) return a.tier - b.tier;
  const aEta = a.etaMs ?? Number.POSITIVE_INFINITY;
  const bEta = b.etaMs ?? Number.POSITIVE_INFINITY;
  if (aEta !== bEta) return aEta - bEta;
  if (a.deadlineMs !== b.deadlineMs) return a.deadlineMs - b.deadlineMs;
  return 0;
};
var resolveStatusId = (plan, nowMs) => resolveSmartTaskListStatus({
  pending: plan.pending || plan.latest === null,
  pendingReason: plan.pendingReason,
  diagnosticReasonCode: plan.diagnosticReasonCode,
  planStatus: plan.latest?.planStatus,
  firstActionAtMs: plan.latest?.hours[0]?.startsAtMs ?? null,
  nowMs
});
var resolveRowCopy = (plan, statusId, firstPlannedTimeLabel) => {
  const detail = resolveSmartTaskWidgetDetailCopy({
    statusId,
    pendingReason: plan.pendingReason,
    floorShortfallCause: plan.latest?.floorShortfallCause,
    dailyBudgetExhaustedBucketCount: plan.latest?.dailyBudgetExhaustedBucketCount,
    firstPlannedTimeLabel
  });
  const suppressPlanMeta = statusId === "cannot_meet" || !plan.latest;
  const suppressConfidence = statusId === "building_plan" && plan.pendingReason === "awaiting_horizon_plan";
  return {
    planMetaLabel: suppressPlanMeta || plan.latest === null ? null : formatPlanMetaLabel(plan.latest),
    confidenceLabel: suppressConfidence ? null : resolveConfidenceLabel(plan.kwhPerUnitProvenance, statusId),
    whyLabel: detail.whyLabel,
    recourseHint: detail.recourseHint
  };
};
var buildRow = (params) => {
  const { deviceId, plan, device, targetValue, statusId, finishMs, nowMs, timeZone } = params;
  const finiteFinish = isFiniteNumber(finishMs) ? finishMs : null;
  const firstHourMs = plan.latest?.hours[0]?.startsAtMs ?? null;
  const firstPlannedTimeLabel = isFiniteNumber(firstHourMs) ? formatLocalHHMM(firstHourMs, timeZone) : null;
  const copy = resolveRowCopy(plan, statusId, firstPlannedTimeLabel);
  const currentValue = resolveCurrentValue(device, plan.objectiveKind);
  return {
    deviceId,
    deviceName: device?.name ?? plan.deviceName ?? deviceId,
    kind: plan.objectiveKind,
    unitSymbol: plan.objectiveKind === "temperature" ? "\xB0C" : "%",
    currentValue,
    targetValue,
    finishLabel: finiteFinish !== null ? formatLocalHHMM(finiteFinish, timeZone) : null,
    statusLabel: SMART_TASK_WIDGET_STATUS_LABELS[statusId],
    tone: STATUS_TONE[statusId],
    etaVerb: resolveSmartTaskWidgetEtaVerb(statusId === "cannot_meet"),
    targetActionVerb: resolveSmartTaskWidgetTargetActionVerb(plan.objectiveKind),
    targetNoun: SMART_TASK_WIDGET_TARGET_NOUN,
    deadlineLongLabel: finiteFinish !== null ? formatDeadlineLong(finiteFinish, nowMs, timeZone) : null,
    planMetaLabel: copy.planMetaLabel,
    confidenceLabel: copy.confidenceLabel,
    whyLabel: copy.whyLabel,
    recourseHint: copy.recourseHint,
    chart: toWidgetChart(resolveActivePlanChartData(plan, { nowMs, currentValue }))
  };
};
var buildCandidate = (params) => {
  const { deviceId, plan, devicesById, nowMs, timeZone } = params;
  if (!isFiniteNumber(plan.deadlineAtMs)) return null;
  const statusId = resolveStatusId(plan, nowMs);
  if (statusId === "satisfied") return null;
  const targetValue = resolveTargetValue(plan);
  if (targetValue === null) return null;
  const etaMs = resolvePlannerEtaMs(plan);
  const row = buildRow({
    deviceId,
    plan,
    device: devicesById.get(deviceId),
    targetValue,
    statusId,
    finishMs: plan.deadlineAtMs,
    nowMs,
    timeZone
  });
  return { row, tier: STATUS_TIER[statusId], etaMs, deadlineMs: plan.deadlineAtMs };
};
var resolveEndedTarget = (entry) => {
  if (entry.objectiveKind === "temperature") {
    return isFiniteNumber(entry.targetTemperatureC) ? entry.targetTemperatureC : null;
  }
  return isFiniteNumber(entry.targetPercent) ? entry.targetPercent : null;
};
var endedRunWasBudgetBound = (entry) => ((entry.finalPlan ?? entry.originalPlan)?.dailyBudgetExhaustedBucketCount ?? 0) > 0;
var resolveEndedRecourse = (entry) => {
  if (entry.outcome !== "missed") return null;
  return endedRunWasBudgetBound(entry) ? RECOURSE_CANNOT_MEET_BUDGET : RECOURSE_CANNOT_MEET_DEVICE;
};
var buildEndedRow = (entry, devicesById, nowMs, timeZone) => {
  const targetValue = resolveEndedTarget(entry);
  if (targetValue === null) return null;
  return {
    id: entry.id,
    deviceId: entry.deviceId,
    deviceName: devicesById.get(entry.deviceId)?.name ?? entry.deviceName ?? entry.deviceId,
    unitSymbol: entry.objectiveKind === "temperature" ? "\xB0C" : "%",
    targetValue,
    targetActionVerb: resolveSmartTaskWidgetTargetActionVerb(entry.objectiveKind),
    outcomeLabel: getPlanHistoryOutcomeLabel(entry.outcome),
    // The history tone vocabulary ('ok' | 'warn' | 'muted') is a subset of the
    // widget tone union, so it maps straight through with no 'danger' case.
    outcomeTone: getPlanHistoryOutcomeTone(entry.outcome),
    finishedLabel: formatDeadlineLong(entry.finalizedAtMs, nowMs, timeZone),
    // Canonical history copy — same helpers the settings-UI history list/detail
    // use, so wording stays single-sourced.
    progressLabel: formatPlanHistoryProgressLine(entry),
    reachedAtLabel: formatPlanHistoryReachedAtLine(entry, timeZone ?? "UTC"),
    whyLabel: formatPlanHistoryMissedReason(entry),
    recourseHint: resolveEndedRecourse(entry),
    chart: toWidgetChart(resolveHistoryDetailChartData(entry))
  };
};
var buildEndedRows = (history, devicesById, nowMs, timeZone) => {
  const byDevice = history?.entriesByDeviceId;
  if (!byDevice) return [];
  const cutoffMs = nowMs - ENDED_WINDOW_MS;
  const recent = Object.values(byDevice).flat().filter((entry) => isFiniteNumber(entry.finalizedAtMs) && entry.finalizedAtMs >= cutoffMs && entry.finalizedAtMs <= nowMs);
  return [...recent].sort((a, b) => b.finalizedAtMs - a.finalizedAtMs).map((entry) => buildEndedRow(entry, devicesById, nowMs, timeZone)).filter((row) => row !== null).slice(0, ENDED_ROW_CAP);
};
var buildSmartTasksWidgetPayload = (input) => {
  const devicesById = new Map(
    input.devices.map((device) => [device.id, device])
  );
  const timeZone = input.timeZone ?? null;
  const endedRows = buildEndedRows(input.history, devicesById, input.nowMs, timeZone);
  const plans = input.activePlans?.plansByDeviceId;
  const candidates = plans ? Object.entries(plans).map(([deviceId, plan]) => plan ? buildCandidate({ deviceId, plan, devicesById, nowMs: input.nowMs, timeZone }) : null).filter((candidate) => candidate !== null) : [];
  if (candidates.length === 0 && endedRows.length === 0) {
    return emptyPayload(EMPTY_SUBTITLE_DEFAULT, SMART_TASK_WIDGET_EMPTY_HINT);
  }
  const sorted = [...candidates].sort(compareCandidates);
  const top = sorted.slice(0, ROW_CAP);
  const overflowCount = Math.max(0, sorted.length - top.length);
  return {
    state: "ready",
    rows: top.map((candidate) => candidate.row),
    overflowCount,
    endedRows
  };
};
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  EMPTY_SUBTITLE_DEFAULT,
  ENDED_ROW_CAP,
  ENDED_WINDOW_MS,
  ROW_CAP,
  buildSmartTasksWidgetPayload
});
