/* Generated by `npm run build:widgets`. Do not edit directly. */
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// widgets/smart_tasks/src/smartTasksWidgetPayload.ts
var smartTasksWidgetPayload_exports = {};
__export(smartTasksWidgetPayload_exports, {
  EMPTY_SUBTITLE_DEFAULT: () => EMPTY_SUBTITLE_DEFAULT,
  ROW_CAP: () => ROW_CAP,
  buildSmartTasksWidgetPayload: () => buildSmartTasksWidgetPayload
});
module.exports = __toCommonJS(smartTasksWidgetPayload_exports);

// packages/shared-domain/src/deadlineLabels.ts
var PENDING_REASON_MISSING_CAPACITY_COPY = "Learning energy use \u2014 needs power readings from this device.";
var SMART_TASK_LIST_STATUS_LABELS = {
  building_plan: "Building plan\u2026",
  queued: "Scheduled",
  paused_unplugged: "Paused \u2014 unplugged",
  on_track: "On track",
  at_risk: "At risk",
  cannot_meet: "Cannot finish",
  satisfied: "Satisfied"
};
var SMART_TASK_WIDGET_STATUS_LABELS = {
  ...SMART_TASK_LIST_STATUS_LABELS,
  paused_unplugged: "Unplugged"
};
var SMART_TASK_WIDGET_WHY_BY_STATUS = {
  building_plan: null,
  // resolved by pendingReason
  queued: null,
  // composed from firstPlannedTimeLabel when present
  paused_unplugged: "EV is unplugged \u2014 plug in to resume.",
  on_track: null,
  // affirmative line resolved from firstPlannedTimeLabel
  at_risk: null,
  // disambiguated by budget vs time below
  cannot_meet: null,
  // resolved by floor cause / budget bucket count
  satisfied: null
};
var SMART_TASK_WIDGET_WHY_BY_PENDING_REASON = {
  awaiting_horizon_plan: "Waiting for tomorrow\u2019s prices.",
  device_data_missing: "Waiting for a reading from this device.",
  invalid_session: "EV is unplugged \u2014 plug in to start.",
  missing_capacity: "Learning energy use from this device.",
  price_feature_disabled: "Price-aware planning is off."
};
var WHY_CANNOT_MEET_BUDGET = "Today\u2019s daily budget runs out before the deadline.";
var WHY_CANNOT_MEET_DEVICE = "Not enough delivery before the deadline.";
var WHY_AT_RISK_BUDGET = "Today\u2019s daily budget may run out before the deadline.";
var WHY_AT_RISK_TIME = "Limited time left before the deadline.";
var RECOURSE_CANNOT_MEET_BUDGET = "Lower the daily budget so future days reserve power earlier.";
var RECOURSE_CANNOT_MEET_DEVICE = "Open this device\u2019s settings in the PELS app to see what\u2019s holding it back.";
var RECOURSE_INVALID_SESSION = "Plug the EV in to resume.";
var isBudgetDriven = (input) => {
  if (input.floorShortfallCause !== void 0) return input.floorShortfallCause === "budget";
  return input.statusId === "at_risk" && (input.dailyBudgetExhaustedBucketCount ?? 0) > 0;
};
var resolveSmartTaskWidgetDetailCopy = (input) => {
  if (input.statusId === "cannot_meet") {
    return isBudgetDriven(input) ? { whyLabel: WHY_CANNOT_MEET_BUDGET, recourseHint: RECOURSE_CANNOT_MEET_BUDGET } : { whyLabel: WHY_CANNOT_MEET_DEVICE, recourseHint: RECOURSE_CANNOT_MEET_DEVICE };
  }
  if (input.statusId === "at_risk") {
    return isBudgetDriven(input) ? { whyLabel: WHY_AT_RISK_BUDGET, recourseHint: RECOURSE_CANNOT_MEET_BUDGET } : { whyLabel: WHY_AT_RISK_TIME, recourseHint: null };
  }
  if (input.statusId === "building_plan") {
    const reason = input.pendingReason ?? "awaiting_horizon_plan";
    const why = SMART_TASK_WIDGET_WHY_BY_PENDING_REASON[reason] ?? SMART_TASK_WIDGET_WHY_BY_PENDING_REASON.awaiting_horizon_plan ?? null;
    return {
      whyLabel: why,
      recourseHint: reason === "invalid_session" ? RECOURSE_INVALID_SESSION : null
    };
  }
  if (input.statusId === "queued" && input.firstPlannedTimeLabel) {
    return {
      whyLabel: `Cheaper hours start at ${input.firstPlannedTimeLabel}.`,
      recourseHint: null
    };
  }
  return {
    whyLabel: SMART_TASK_WIDGET_WHY_BY_STATUS[input.statusId],
    recourseHint: null
  };
};
var SMART_TASK_WIDGET_EMPTY_HINT = "Add a smart task from a Flow card to see it here.";
var SMART_TASK_WIDGET_EMPTY_SUBTITLE = "No active smart tasks";
var SMART_TASK_WIDGET_PLAN_META_LABEL_PREFIX = "Estimate";
var resolveBuildingPlanChipTone = () => "info";
var resolvePausedUnpluggedChipTone = () => "warn";
var SMART_TASK_LIST_STATUS_CHIP_VARIANT = {
  building_plan: resolveBuildingPlanChipTone(),
  queued: "muted",
  paused_unplugged: resolvePausedUnpluggedChipTone(),
  on_track: "ok",
  at_risk: "warn",
  cannot_meet: "alert",
  satisfied: "ok"
};
var SMART_TASK_LIST_READY_BY_STATUS_WORD = {
  building_plan: null,
  queued: null,
  // The inline word is joined to the timestamp with an em-dash separator
  // ("Ready by … — <word>"). For paused we use the compressed widget label
  // ('Unplugged') rather than the full chip label ('Paused — unplugged'): the
  // latter carries its own em-dash, which would render a confusing double-dash
  // ("… — Paused — unplugged") on the Ready-by line. The chip still shows the
  // full label; this is the same sanctioned shared-domain string, not a new
  // variant.
  paused_unplugged: SMART_TASK_WIDGET_STATUS_LABELS.paused_unplugged,
  on_track: null,
  at_risk: SMART_TASK_LIST_STATUS_LABELS.at_risk,
  cannot_meet: SMART_TASK_LIST_STATUS_LABELS.cannot_meet,
  satisfied: null
};
var formatConfidenceChipLabel = (confidence) => {
  if (confidence === "low") return "Estimating";
  if (confidence === "medium") return "Refining";
  return null;
};
var MIN_LEARNED_SAMPLES_FOR_CONFIDENT_CHIP = 4;
var resolveSmartTaskLearning = (provenance) => {
  if (!provenance) return false;
  if (provenance.source === "bootstrap") return true;
  return provenance.acceptedSamples < MIN_LEARNED_SAMPLES_FOR_CONFIDENT_CHIP;
};
var formatSmartTaskListConfidenceChipLabel = (params) => {
  if (params.statusId === "cannot_meet" || params.statusId === "on_track") return null;
  if (!params.learning) return null;
  return formatConfidenceChipLabel(params.confidence);
};
var SMART_TASK_LIST_ROW_LABELS = {
  target: "Target",
  starts: "Starts",
  readyBy: "Ready by"
};
var SMART_TASK_WIDGET_DUE_VERB = "Due";
var resolveSmartTaskWidgetEtaVerb = (isFailing) => isFailing ? SMART_TASK_WIDGET_DUE_VERB : SMART_TASK_LIST_ROW_LABELS.readyBy;
var SMART_TASK_WIDGET_TARGET_ACTION_VERB = {
  temperature: "Heat to",
  ev_soc: "Charge to"
};
var resolveSmartTaskWidgetTargetActionVerb = (kind) => SMART_TASK_WIDGET_TARGET_ACTION_VERB[kind];
var SMART_TASK_WIDGET_TARGET_NOUN = SMART_TASK_LIST_ROW_LABELS.target;
var resolveSmartTaskListStatus = (params) => {
  const { pending, pendingReason, diagnosticReasonCode, planStatus, firstActionAtMs, nowMs } = params;
  if (diagnosticReasonCode === "objective_invalid_session") return "paused_unplugged";
  if (pending || planStatus === void 0) {
    if (pendingReason === "invalid_session") return "paused_unplugged";
    return "building_plan";
  }
  if (firstActionAtMs !== null && firstActionAtMs > nowMs) return "queued";
  if (planStatus === "satisfied") return "satisfied";
  if (planStatus === "cannot_meet") return "cannot_meet";
  if (planStatus === "at_risk") return "at_risk";
  return "on_track";
};
var REVISION_REASON_TOOLTIP_LINE = {
  flow_card: "Updated after a flow card fired",
  prices_arrived: "Updated as prices became available",
  objective_changed: "Updated after the target changed",
  // Only fires when the planner consumed a newer price horizon than the
  // previous revision. `schedule_revised` carries internal replans.
  prices_revised: "Updated as new prices arrived",
  // Schedule shifted without a new price horizon — daily-budget pressure
  // moved a bucket, planStatus flipped, etc. Honest about the cause without
  // claiming a publication event.
  schedule_revised: "Updated as the schedule was revised",
  rate_refined: "Updated as rates were refined",
  flow_permission_changed: "Updated after a Flow changed what this smart task may do"
};
var SCHEDULE_REVISED_BASE = "Schedule revised";
var SCHEDULE_REVISED_BUDGET = `${SCHEDULE_REVISED_BASE} \u2014 daily budget shifted`;
var SCHEDULE_REVISED_RISK = `${SCHEDULE_REVISED_BASE} \u2014 risk changed`;
var SCHEDULE_REVISED_OPENED = `${SCHEDULE_REVISED_BASE} \u2014 cheaper hour opened`;
var withLastFetched = (base, lastFetchedShort) => lastFetchedShort ? `${base} Last price update: ${lastFetchedShort}.` : base;
var resolveQueuedHeadlineReason = (params) => {
  if (params.pricesShortOfDeadline) {
    return `Waiting for tomorrow\u2019s prices through ${params.deadlineTime}.`;
  }
  if (params.dailyBudgetExhausted) {
    return "Today\u2019s budget is full \u2014 next cheap window after midnight.";
  }
  return `Cheaper than now \u2014 starts at ${params.firstPlannedTime}.`;
};
var CANNOT_MEET_RECOURSE = {
  openBudget: { label: "Open Budget", targetTab: "budget" },
  openOverview: { label: "Adjust device", targetTab: "overview" }
};
var OVERVIEW_DEVICE_RECOURSE_BASE = { label: "Open device in Overview", targetTab: "overview" };
var overviewDeviceRecourse = (deviceId) => ({ ...OVERVIEW_DEVICE_RECOURSE_BASE, deviceId });
var awaitingHorizonCopy = (kindNoun) => ((ctx) => {
  const isFlow = ctx.priceSource === "external_flow";
  const body = isFlow ? `PELS needs prices through the deadline before it can build a ${kindNoun}. In flow price mode, prices arrive only when a Flow calls the \u201CSet external prices (tomorrow)\u201D action. Check the Flow that publishes prices if this message stays up after tomorrow\u2019s prices should have arrived.` : `PELS will build a ${kindNoun} as soon as prices through the deadline are available.`;
  return {
    headline: isFlow ? "Waiting for tomorrow\u2019s prices from your Flow" : "Waiting for tomorrow\u2019s prices",
    body: withLastFetched(body, ctx.lastFetchedShort),
    // Avoid restating "Waiting for tomorrow’s prices" from the headline; the
    // panic-visitor's actionable detail is the horizon time the planner
    // needs to cover.
    headlineReason: `Need prices through ${ctx.deadlineTime} before the smart task can start.`,
    recourse: null
  };
});
var deviceDataMissingResolver = (kind) => (ctx) => ({
  headline: kind.headline,
  body: kind.body,
  headlineReason: `PELS can\u2019t read the ${kind.readingNoun} from ${ctx.deviceName.trim() || kind.fallbackDeviceNoun}.`,
  recourse: overviewDeviceRecourse(ctx.deviceId)
});
var [MISSING_CAPACITY_HEADLINE, MISSING_CAPACITY_BODY_FRAGMENT] = PENDING_REASON_MISSING_CAPACITY_COPY.split(" \u2014 ");
var MISSING_CAPACITY_BODY = `${MISSING_CAPACITY_BODY_FRAGMENT[0].toUpperCase()}${MISSING_CAPACITY_BODY_FRAGMENT.slice(1)}`;
var HEATER_DEVICE_DATA_MISSING = deviceDataMissingResolver({
  headline: "Waiting for a reading from the device",
  body: "PELS needs a current temperature, a useful capacity, or a recent observation from this heater before it can plan the smart task.",
  readingNoun: "current temperature",
  fallbackDeviceNoun: "the heater"
});
var EV_DEVICE_DATA_MISSING = deviceDataMissingResolver({
  headline: "Waiting for a reading from the EV",
  body: "PELS needs a current state of charge, a charge rate, or a recent observation from this EV before it can plan the smart task.",
  readingNoun: "state of charge",
  fallbackDeviceNoun: "the EV"
});
var DEADLINE_LABELS = {
  temperature: {
    kindChipLabel: "Temperature",
    activeChipLabel: "Heating",
    sectionLabel: "Heating smart task",
    liveStateChipLabel: {
      active: "Heating",
      building_plan: "Building plan\u2026",
      queued: "Scheduled",
      // Thermal devices can't be unplugged; the variant is unreachable here
      // and falls back to the generic scheduled copy if the resolver ever
      // hands a stale value through.
      paused_unplugged: "Scheduled",
      ok: "On track"
    },
    atRiskChipLabel: SMART_TASK_LIST_STATUS_LABELS.at_risk,
    cannotMeetChipLabel: "Cannot finish",
    deviceSeriesName: "Heating",
    originalDeviceSeriesName: "Original Heating",
    actualDeviceSeriesName: "Measured Heating",
    backgroundSeriesName: "Background usage",
    progressSeriesName: "Temperature",
    planTooltipIdle: "Idle",
    // Thermal `invalid_session` is unreachable today (heaters can't be
    // unplugged); we map it to `device_data_missing` so a future diagnostic
    // can't leak EV-specific copy. `missing_capacity` is the cold-start
    // "learning energy profile" state — no shipped bootstrap kWh/°C — and
    // recourse lands on Overview where the user can verify the heater is
    // actually running and reporting power.
    pendingHeroByReason: {
      awaiting_horizon_plan: awaitingHorizonCopy("heat plan"),
      price_feature_disabled: () => ({
        headline: "Price-aware optimisation is off",
        body: "Enable price-aware optimisation in Settings \u2192 Electricity prices to compute a heat plan.",
        headlineReason: "Price-aware optimisation is off in Settings.",
        recourse: { label: "Open Settings", targetTab: "settings" }
      }),
      device_data_missing: HEATER_DEVICE_DATA_MISSING,
      invalid_session: HEATER_DEVICE_DATA_MISSING,
      // Cold-start `missing_capacity` collapses to a single user-facing line —
      // headline + metaLine combined parse as `PENDING_REASON_MISSING_CAPACITY_COPY`
      // ("Learning energy use — needs power readings from this device."). Earlier
      // copy split the explanation across body + headlineReason, which buried the
      // "give it power readings" lever in a paragraph. The pending-reason path
      // here intentionally addresses only `objective_missing_capacity`
      // (no-profile cold-start); the thermal `objective_missing_charge_rate`
      // fall-through still routes to this resolver via `THERMAL_LEARNING_CAPACITY_REASON_CODES`
      // in the recorder, which is the same "still learning" user state from
      // their point of view.
      missing_capacity: (ctx) => ({
        headline: MISSING_CAPACITY_HEADLINE,
        body: MISSING_CAPACITY_BODY,
        headlineReason: null,
        recourse: overviewDeviceRecourse(ctx.deviceId)
      })
    },
    unavailableByReason: {
      no_current_reading: {
        headline: "Waiting for the first temperature reading",
        body: "The schedule will appear once the device reports its current temperature."
      },
      already_satisfied: {
        headline: "Satisfied",
        body: "The current temperature already meets the smart task target. PELS will schedule it again if the temperature drops below target."
      }
    },
    // Drops the raw progress-unit delta ("Short by about 41.9 °C") that users
    // misread as a wild temperature anomaly. The underlying shortfall is energy
    // / time against the plan, not a raw temperature gap; the chip + headline
    // already say the verdict ("Cannot finish"); body states the cause and the
    // user-side levers. The hero meta line follows with the "Needs N kWh · Y
    // hours left · …" line via `formatMetaLine`, which is the right surface for
    // magnitude. Recourse copy names the two levers that aren't the daily
    // budget; the budget remedy is handled by the dedicated
    // `cannotMeetDailyBudgetExhausted` branch above.
    cannotMeetShortfall: () => "Not enough time for this target. Lower the target or move the deadline.",
    cannotMeetDailyBudgetExhausted: "Today's daily budget is fully booked. Lower it so future days reserve power earlier, or move the deadline.",
    cannotMeetRecourse: CANNOT_MEET_RECOURSE,
    resolveQueuedHeadlineReason,
    completedHero: {
      headline: "Smart task finished",
      body: "See Smart tasks for the outcome."
    },
    targetUnit: "\xB0C",
    planInputsCardTitle: "What PELS has learned",
    planInputsRateRowLabel: "Energy needed per \xB0C",
    planInputsMaxPowerRowLabel: "Device power used",
    perUnitRateUnit: "kWh/\xB0C",
    planInputsRateBootstrapNote: null,
    revisionReasonTooltipLine: REVISION_REASON_TOOLTIP_LINE
  },
  ev_soc: {
    kindChipLabel: "EV",
    activeChipLabel: "Charging",
    sectionLabel: "EV smart task",
    liveStateChipLabel: {
      active: "Charging",
      building_plan: "Building plan\u2026",
      queued: "Scheduled",
      paused_unplugged: "Paused \u2014 unplugged",
      ok: "On track"
    },
    atRiskChipLabel: SMART_TASK_LIST_STATUS_LABELS.at_risk,
    cannotMeetChipLabel: "Cannot finish",
    deviceSeriesName: "Charging",
    originalDeviceSeriesName: "Original Charging",
    actualDeviceSeriesName: "Measured Charging",
    backgroundSeriesName: "Background usage",
    progressSeriesName: "Charge level",
    planTooltipIdle: "Idle",
    // EV `invalid_session` is the plugged-out / discharging pause state. The
    // body already says "PELS will resume…", the headlineReason restates the
    // *cause* at headline height, and recourse is null because plugging in
    // is a physical action with no in-app tab to land on. EV
    // `missing_capacity` should never fire (bootstrap fallback exists); the
    // device-data-missing copy is kept as a safety net.
    pendingHeroByReason: {
      awaiting_horizon_plan: awaitingHorizonCopy("charging plan"),
      price_feature_disabled: () => ({
        headline: "Price-aware optimisation is off",
        body: "Enable price-aware optimisation in Settings \u2192 Electricity prices to compute a charging plan.",
        headlineReason: "Price-aware optimisation is off in Settings.",
        recourse: { label: "Open Settings", targetTab: "settings" }
      }),
      device_data_missing: EV_DEVICE_DATA_MISSING,
      invalid_session: () => ({
        headline: "Charging paused \u2014 EV unplugged",
        body: "PELS will resume the schedule once the EV is plugged in and reports a valid charging session.",
        headlineReason: "Charger reports the car isn\u2019t plugged in.",
        recourse: null
      }),
      missing_capacity: EV_DEVICE_DATA_MISSING
    },
    unavailableByReason: {
      no_current_reading: {
        headline: "Waiting for the first state-of-charge reading",
        body: "The schedule will appear once the EV reports its current state of charge."
      },
      already_satisfied: {
        headline: "Satisfied",
        body: "The EV is already at or above the smart task target. PELS will schedule it again if the state of charge drops below target."
      }
    },
    // EV mirrors the thermal copy: drop the raw % shortfall figure (users can
    // read it as "the car lost 30 % of charge") in favour of plain-language
    // recourse. The meta line continues to carry the energy/duration magnitude.
    cannotMeetShortfall: () => "Not enough time or charging power for this target. Lower the target or move the deadline.",
    cannotMeetDailyBudgetExhausted: "Today's daily budget is fully booked. Lower it so future days reserve power earlier, or move the deadline.",
    cannotMeetRecourse: CANNOT_MEET_RECOURSE,
    resolveQueuedHeadlineReason,
    completedHero: {
      headline: "Smart task finished",
      body: "See Smart tasks for the outcome."
    },
    targetUnit: "%",
    planInputsCardTitle: "What PELS has learned",
    planInputsRateRowLabel: "Energy needed per %",
    planInputsMaxPowerRowLabel: "Device power used",
    perUnitRateUnit: "kWh/%",
    planInputsRateBootstrapNote: "Estimated \u2014 refining as PELS observes charging.",
    revisionReasonTooltipLine: REVISION_REASON_TOOLTIP_LINE
  }
};
var EV_CARD_HOUR_MS = 60 * 60 * 1e3;
var SAMPLE_STALE_THRESHOLD_MS = 24 * 60 * 60 * 1e3;
var ONE_MINUTE_MS = 60 * 1e3;
var ONE_HOUR_MS = 60 * ONE_MINUTE_MS;

// widgets/smart_tasks/src/smartTasksWidgetPayload.ts
var ROW_CAP = 3;
var EMPTY_SUBTITLE_DEFAULT = SMART_TASK_WIDGET_EMPTY_SUBTITLE;
var STATUS_TIER = {
  cannot_meet: 0,
  at_risk: 1,
  paused_unplugged: 2,
  building_plan: 2,
  queued: 3,
  on_track: 3,
  satisfied: 99
};
var STATUS_TONE = {
  cannot_meet: "danger",
  at_risk: "warn",
  paused_unplugged: "muted",
  building_plan: "muted",
  queued: "ok",
  on_track: "ok",
  satisfied: "ok"
};
var isFiniteNumber = (value) => typeof value === "number" && Number.isFinite(value);
var resolveCurrentValue = (device, kind) => {
  if (!device) return null;
  if (kind === "temperature") {
    return isFiniteNumber(device.currentTemperature) ? device.currentTemperature : null;
  }
  const percent = device.stateOfCharge?.percent;
  return isFiniteNumber(percent) ? percent : null;
};
var resolveTargetValue = (plan) => {
  if (plan.objectiveKind === "temperature") {
    return isFiniteNumber(plan.targetTemperatureC) ? plan.targetTemperatureC : null;
  }
  return isFiniteNumber(plan.targetPercent) ? plan.targetPercent : null;
};
var resolvePlannerEtaMs = (plan) => {
  const hours = plan.latest?.hours;
  if (!hours || hours.length === 0) return null;
  const last = hours[hours.length - 1];
  return isFiniteNumber(last.startsAtMs) ? last.startsAtMs + 60 * 60 * 1e3 : null;
};
var formatLocalHHMMFallback = (date) => `${String(date.getHours()).padStart(2, "0")}:${String(date.getMinutes()).padStart(2, "0")}`;
var formatLocalHHMM = (ms, timeZone) => {
  const date = new Date(ms);
  if (!Number.isFinite(date.getTime())) return "";
  try {
    return new Intl.DateTimeFormat("en-GB", {
      hour: "2-digit",
      minute: "2-digit",
      hour12: false,
      timeZone: timeZone ?? void 0
    }).format(date);
  } catch {
    return formatLocalHHMMFallback(date);
  }
};
var calendarDayIndex = (ms, timeZone) => {
  try {
    const ymd = new Intl.DateTimeFormat("en-CA", {
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
      timeZone: timeZone ?? void 0
    }).format(new Date(ms));
    const [y, m, d] = ymd.split("-").map(Number);
    return Math.round(Date.UTC(y, m - 1, d) / (24 * 60 * 60 * 1e3));
  } catch {
    const date = new Date(ms);
    return Math.round(
      Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()) / (24 * 60 * 60 * 1e3)
    );
  }
};
var localDayDiff = (deadlineMs, nowMs, timeZone) => calendarDayIndex(deadlineMs, timeZone) - calendarDayIndex(nowMs, timeZone);
var formatDeadlineLong = (ms, nowMs, timeZone) => {
  const date = new Date(ms);
  if (!Number.isFinite(date.getTime())) return "";
  const timePart = formatLocalHHMM(ms, timeZone);
  const dayDiff = localDayDiff(ms, nowMs, timeZone);
  if (dayDiff === 0) return `Today ${timePart}`;
  if (dayDiff === 1) return `Tomorrow ${timePart}`;
  try {
    if (dayDiff >= -6 && dayDiff <= 6) {
      const weekday = new Intl.DateTimeFormat("en-GB", {
        weekday: "short",
        timeZone: timeZone ?? void 0
      }).format(date);
      return `${weekday} ${timePart}`;
    }
    const dayMonth = new Intl.DateTimeFormat("en-GB", {
      day: "numeric",
      month: "short",
      timeZone: timeZone ?? void 0
    }).format(date);
    return `${dayMonth} ${timePart}`;
  } catch {
    return formatLocalHHMMFallback(date);
  }
};
var formatDurationFromHours = (hours) => {
  if (!Number.isFinite(hours) || hours <= 0) return "";
  const totalMinutes = Math.max(1, Math.round(hours * 60));
  const h = Math.floor(totalMinutes / 60);
  const m = totalMinutes % 60;
  if (h === 0) return `${m}m`;
  if (m === 0) return `${h}h`;
  return `${h}h ${m}m`;
};
var formatKwh = (value) => {
  if (!Number.isFinite(value) || value <= 0) return "";
  const rounded = Math.round(value * 10) / 10;
  return `${rounded.toFixed(1)} kWh`;
};
var resolveDurationPart = (revision) => {
  if (revision.estimatedDurationText) return `\u2248${revision.estimatedDurationText}`;
  const speed = revision.planningSpeedKw;
  if (speed && speed > 0 && revision.energyNeededKWh > 0) {
    const dur = formatDurationFromHours(revision.energyNeededKWh / speed);
    return dur ? `\u2248${dur}` : null;
  }
  return null;
};
var resolveSpeedPart = (revision) => {
  const speed = revision.planningSpeedKw;
  if (!speed || speed <= 0) return null;
  return `${(Math.round(speed * 10) / 10).toFixed(1)} kW`;
};
var resolveEnergyPart = (revision) => {
  const expected = revision.energyExpectedKWh;
  const needed = revision.energyNeededKWh;
  if (isFiniteNumber(expected) && expected > 0 && needed > 0 && Math.abs(expected - needed) > 0.05) {
    const low = Math.round(Math.min(expected, needed) * 10) / 10;
    const high = Math.round(Math.max(expected, needed) * 10) / 10;
    return `\u2248${low.toFixed(1)}\u2013${high.toFixed(1)} kWh`;
  }
  if (needed > 0) return `\u2248${formatKwh(needed)}`;
  return null;
};
var formatPlanMetaLabel = (revision) => {
  const parts = [
    resolveDurationPart(revision),
    resolveSpeedPart(revision),
    resolveEnergyPart(revision)
  ].filter((part) => part !== null && part !== "");
  if (parts.length === 0) return null;
  return `${SMART_TASK_WIDGET_PLAN_META_LABEL_PREFIX} ${parts.join(" \xB7 ")}`;
};
var resolveConfidenceLabel = (provenance, statusId) => formatSmartTaskListConfidenceChipLabel({
  confidence: provenance?.displayConfidence ?? provenance?.confidence ?? null,
  statusId,
  learning: resolveSmartTaskLearning(provenance)
});
var emptyPayload = (subtitle, hint) => ({
  state: "empty",
  subtitle,
  hint
});
var compareCandidates = (a, b) => {
  if (a.tier !== b.tier) return a.tier - b.tier;
  const aEta = a.etaMs ?? Number.POSITIVE_INFINITY;
  const bEta = b.etaMs ?? Number.POSITIVE_INFINITY;
  if (aEta !== bEta) return aEta - bEta;
  if (a.deadlineMs !== b.deadlineMs) return a.deadlineMs - b.deadlineMs;
  return 0;
};
var resolveStatusId = (plan, nowMs) => resolveSmartTaskListStatus({
  pending: plan.pending || plan.latest === null,
  pendingReason: plan.pendingReason,
  diagnosticReasonCode: plan.diagnosticReasonCode,
  planStatus: plan.latest?.planStatus,
  firstActionAtMs: plan.latest?.hours[0]?.startsAtMs ?? null,
  nowMs
});
var resolveRowCopy = (plan, statusId, firstPlannedTimeLabel) => {
  const detail = resolveSmartTaskWidgetDetailCopy({
    statusId,
    pendingReason: plan.pendingReason,
    floorShortfallCause: plan.latest?.floorShortfallCause,
    dailyBudgetExhaustedBucketCount: plan.latest?.dailyBudgetExhaustedBucketCount,
    firstPlannedTimeLabel
  });
  const suppressPlanMeta = statusId === "cannot_meet" || !plan.latest;
  const suppressConfidence = statusId === "building_plan" && plan.pendingReason === "awaiting_horizon_plan";
  return {
    planMetaLabel: suppressPlanMeta || plan.latest === null ? null : formatPlanMetaLabel(plan.latest),
    confidenceLabel: suppressConfidence ? null : resolveConfidenceLabel(plan.kwhPerUnitProvenance, statusId),
    whyLabel: detail.whyLabel,
    recourseHint: detail.recourseHint
  };
};
var buildRow = (params) => {
  const { deviceId, plan, device, targetValue, statusId, finishMs, nowMs, timeZone } = params;
  const finiteFinish = isFiniteNumber(finishMs) ? finishMs : null;
  const firstHourMs = plan.latest?.hours[0]?.startsAtMs ?? null;
  const firstPlannedTimeLabel = isFiniteNumber(firstHourMs) ? formatLocalHHMM(firstHourMs, timeZone) : null;
  const copy = resolveRowCopy(plan, statusId, firstPlannedTimeLabel);
  return {
    deviceId,
    deviceName: device?.name ?? plan.deviceName ?? deviceId,
    kind: plan.objectiveKind,
    unitSymbol: plan.objectiveKind === "temperature" ? "\xB0C" : "%",
    currentValue: resolveCurrentValue(device, plan.objectiveKind),
    targetValue,
    finishLabel: finiteFinish !== null ? formatLocalHHMM(finiteFinish, timeZone) : null,
    statusLabel: SMART_TASK_WIDGET_STATUS_LABELS[statusId],
    tone: STATUS_TONE[statusId],
    etaVerb: resolveSmartTaskWidgetEtaVerb(statusId === "cannot_meet"),
    targetActionVerb: resolveSmartTaskWidgetTargetActionVerb(plan.objectiveKind),
    targetNoun: SMART_TASK_WIDGET_TARGET_NOUN,
    deadlineLongLabel: finiteFinish !== null ? formatDeadlineLong(finiteFinish, nowMs, timeZone) : null,
    planMetaLabel: copy.planMetaLabel,
    confidenceLabel: copy.confidenceLabel,
    whyLabel: copy.whyLabel,
    recourseHint: copy.recourseHint
  };
};
var buildCandidate = (params) => {
  const { deviceId, plan, devicesById, nowMs, timeZone } = params;
  if (!isFiniteNumber(plan.deadlineAtMs)) return null;
  const statusId = resolveStatusId(plan, nowMs);
  if (statusId === "satisfied") return null;
  const targetValue = resolveTargetValue(plan);
  if (targetValue === null) return null;
  const etaMs = resolvePlannerEtaMs(plan);
  const row = buildRow({
    deviceId,
    plan,
    device: devicesById.get(deviceId),
    targetValue,
    statusId,
    finishMs: plan.deadlineAtMs,
    nowMs,
    timeZone
  });
  return { row, tier: STATUS_TIER[statusId], etaMs, deadlineMs: plan.deadlineAtMs };
};
var buildSmartTasksWidgetPayload = (input) => {
  const plans = input.activePlans?.plansByDeviceId;
  if (!plans) return emptyPayload(EMPTY_SUBTITLE_DEFAULT, SMART_TASK_WIDGET_EMPTY_HINT);
  const devicesById = new Map(
    input.devices.map((device) => [device.id, device])
  );
  const candidates = Object.entries(plans).map(([deviceId, plan]) => plan ? buildCandidate({ deviceId, plan, devicesById, nowMs: input.nowMs, timeZone: input.timeZone ?? null }) : null).filter((candidate) => candidate !== null);
  if (candidates.length === 0) return emptyPayload(EMPTY_SUBTITLE_DEFAULT, SMART_TASK_WIDGET_EMPTY_HINT);
  const sorted = [...candidates].sort(compareCandidates);
  const top = sorted.slice(0, ROW_CAP);
  const overflowCount = Math.max(0, sorted.length - top.length);
  return {
    state: "ready",
    rows: top.map((candidate) => candidate.row),
    overflowCount
  };
};
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  EMPTY_SUBTITLE_DEFAULT,
  ROW_CAP,
  buildSmartTasksWidgetPayload
});
