/* Generated by `npm run build:widgets`. Do not edit directly. */
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var api_exports = {};
__export(api_exports, {
  getChart: () => getChart
});
module.exports = __toCommonJS(api_exports);
var import_planPriceWidgetPayload = require("./planPriceWidgetPayload");
const COMBINED_PRICES_SETTING = "combined_prices";
const collectV2Hours = (days) => Object.values(days).flatMap((day) => {
  if (!day || typeof day !== "object") return [];
  const hours = day.hours;
  return Array.isArray(hours) ? hours : [];
});
const flattenStoreToCombinedPriceData = (value) => {
  if (!value || typeof value !== "object") return null;
  const record = value;
  const isV2 = record.days && typeof record.days === "object" && !Array.isArray(record.days);
  const isV1 = Array.isArray(record.prices);
  if (!isV2 && !isV1) return null;
  const collected = isV2 ? collectV2Hours(record.days) : record.prices;
  const prices = [...collected].sort(
    (a, b) => new Date(a.startsAt).getTime() - new Date(b.startsAt).getTime()
  );
  return {
    prices,
    lastFetched: typeof record.lastFetched === "string" ? record.lastFetched : void 0,
    priceUnit: typeof record.priceUnit === "string" ? record.priceUnit : void 0
  };
};
const getChart = async ({ homey, query }) => {
  const app = homey.app;
  const snapshot = typeof app?.getDailyBudgetUiPayload === "function" ? app.getDailyBudgetUiPayload() : null;
  const combinedPrices = flattenStoreToCombinedPriceData(homey.settings.get(COMBINED_PRICES_SETTING));
  return (0, import_planPriceWidgetPayload.buildPlanPriceWidgetPayload)({
    snapshot,
    combinedPrices,
    target: query?.day
  });
};
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  getChart
});
