/* Generated by `npm run build:widgets`. Do not edit directly. */
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var api_exports = {};
__export(api_exports, {
  getChart: () => getChart
});
module.exports = __toCommonJS(api_exports);
var import_planPriceWidgetPayload = require("./planPriceWidgetPayload");
const COMBINED_PRICES_SETTING = "combined_prices";
const isCombinedPriceData = (value) => typeof value === "object" && value !== null;
const getChart = async ({ homey, query }) => {
  const app = homey.app;
  const snapshot = typeof app?.getDailyBudgetUiPayload === "function" ? app.getDailyBudgetUiPayload() : null;
  const combinedPricesValue = homey.settings.get(COMBINED_PRICES_SETTING);
  return (0, import_planPriceWidgetPayload.buildPlanPriceWidgetPayload)({
    snapshot,
    combinedPrices: isCombinedPriceData(combinedPricesValue) ? combinedPricesValue : null,
    target: query?.day
  });
};
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  getChart
});
