import type Homey from 'homey';
import type CapacityGuard from '../core/capacityGuard';
import type { DeviceManager } from '../core/deviceManager';
import type { PowerTrackerState } from '../core/powerTracker';
import type { DailyBudgetService } from '../dailyBudget/dailyBudgetService';
import type { DailyBudgetUiPayload } from '../dailyBudget/dailyBudgetTypes';
import type { DeviceDiagnosticsService } from '../diagnostics/deviceDiagnosticsService';
import type { Logger as PinoLogger, StructuredDebugEmitter } from '../logging/logger';
import type { HeadroomForDeviceDecision } from '../plan/planHeadroomDevice';
import type { PlanEngine } from '../plan/planEngine';
import type { PendingTargetObservationSource, DevicePlan, ShedAction, ShedBehavior } from '../plan/planTypes';
import type { PlanService } from '../plan/planService';
import type { PriceLevel } from '../price/priceLevels';
import type { PriceCoordinator } from '../price/priceCoordinator';
import type { PriceOptimizationSettings } from '../price/priceOptimizer';
import type { DebugLoggingTopic } from '../utils/debugLogging';
import type { DeviceControlProfiles, TargetDeviceSnapshot } from '../utils/types';
import type { HomeyDeviceLike } from '../utils/types';
import type { AppDeviceControlHelpers } from './appDeviceControlHelpers';
import type { AppHomeyEnergyHelpers } from './appHomeyEnergyHelpers';
import type { PowerSampleRebuildState } from './appPowerHelpers';
import type { PlanRebuildScheduler } from './planRebuildScheduler';
import type { RefreshTargetDevicesSnapshotOptions, AppSnapshotHelpers } from './appSnapshotHelpers';
import type { TimerRegistry } from './timerRegistry';
import type { FlowReportedCapabilitiesForDevice, FlowReportedCapabilityId } from '../core/flowReportedCapabilities';

export type FlowBackedCapabilityReportOutcome = {
  kind: 'state_changed' | 'freshness_only' | 'noop';
  valueChanged: boolean;
  freshnessAdvanced: boolean;
  refreshSnapshot: boolean;
  rebuildPlan: boolean;
};

export type StartupBootstrapConfig = {
  snapshotPlanBootstrapDelayMs?: number;
  overheadTokenDelayMs?: number;
  runSnapshotPlanBootstrapInBackground?: boolean;
  runPriceBootstrapInBackground?: boolean;
  applyPriceOptimizationImmediatelyOnStart?: boolean;
};

export type AppContext = {
  startupBootstrap?: StartupBootstrapConfig;
  homey: Homey.App['homey'];
  log: (...args: unknown[]) => void;
  error: (...args: unknown[]) => void;
  logDebug: (topic: DebugLoggingTopic, ...args: unknown[]) => void;
  getStructuredLogger: (component: string) => PinoLogger | undefined;
  getStructuredDebugEmitter: (component: string, debugTopic: DebugLoggingTopic) => StructuredDebugEmitter;
  getNow: () => Date;
  getTimeZone: () => string;
  notifyOperatingModeChanged: (mode: string) => void;
  loadPowerTracker: (options?: { skipDailyBudgetUpdate?: boolean }) => void;
  loadCapacitySettings: () => void;
  loadPriceOptimizationSettings: () => void;
  updatePriceOptimizationEnabled: (logChange?: boolean) => void;
  updateDebugLoggingEnabled: (logChange?: boolean) => void;
  updateOverheadToken: (value?: number) => Promise<void>;
  registerFlowCards: () => void;
  refreshTargetDevicesSnapshot: (options?: RefreshTargetDevicesSnapshotOptions) => Promise<void>;
  recordPowerSample: (powerW: number, nowMs?: number) => Promise<void>;
  startHeartbeat: () => void;
  handleOperatingModeChange: (rawMode: string) => Promise<void>;
  getFlowSnapshot: () => Promise<TargetDeviceSnapshot[]>;
  getCurrentPriceLevel: () => PriceLevel;
  isCurrentHourCheap: () => boolean;
  isCurrentHourExpensive: () => boolean;
  areFlowBackedCardsAvailable: () => boolean;
  getDeviceLoadSetting: (deviceId: string) => Promise<number | null>;
  setExpectedOverride: (deviceId: string, kw: number) => boolean;
  storeFlowPriceData: (kind: 'today' | 'tomorrow', raw: unknown) => {
    dateKey: string;
    storedCount: number;
    missingHours: number[];
  };
  loadDailyBudgetSettings: () => void;
  updateDailyBudgetState: (options?: { nowMs?: number; forcePlanRebuild?: boolean }) => void;
  disableManagedEvDevices: () => void;
  requestFlowPlanRebuild: (source: string) => void;
  getFlowReportedCapabilitiesForDevice: (deviceId: string) => FlowReportedCapabilitiesForDevice;
  getFlowReportedDeviceIds: () => string[];
  reportFlowBackedCapability: (params: {
    deviceId: string;
    capabilityId: FlowReportedCapabilityId;
    value: boolean | number | string;
  }) => FlowBackedCapabilityReportOutcome;
  getHomeyDevicesForFlow: () => Promise<HomeyDeviceLike[]>;
  emitFlowBackedRefreshRequests: (deviceIds: string[]) => Promise<void>;
  getPriorityForDevice: (deviceId: string) => number;
  resolveModeName: (name: string) => string;
  getAllModes: () => Set<string>;
  resolveManagedState: (deviceId: string) => boolean;
  getCommunicationModel: (deviceId: string) => 'local' | 'cloud';
  isCapacityControlEnabled: (deviceId: string) => boolean;
  isBudgetExempt: (deviceId: string) => boolean;
  getShedBehavior: (deviceId: string) => {
    action: ShedAction;
    temperature: number | null;
    stepId: string | null;
  };
  computeDynamicSoftLimit: () => number;
  getDynamicSoftLimitOverride: () => number | null;
  logTargetRetryComparison?: (params: {
    deviceId: string;
    name: string;
    targetCap: string;
    desired: number;
    observedValue?: unknown;
    observedSource?: string;
    retryCount: number;
    skipContext: 'plan' | 'shedding' | 'overshoot';
  }) => Promise<void> | void;
  syncLivePlanStateAfterTargetActuation?: (source: PendingTargetObservationSource) => boolean | void;
  evaluateHeadroomForDevice: (
    params: Parameters<PlanService['evaluateHeadroomForDevice']>[0],
  ) => HeadroomForDeviceDecision | null;
  getCombinedHourlyPrices: () => unknown;
  getDailyBudgetUiPayload: () => DailyBudgetUiPayload | null;
  getLatestPlanSnapshotForUi: () => DevicePlan | null;
  get powerTracker(): PowerTrackerState;
  set powerTracker(value: PowerTrackerState);
  get capacitySettings(): { limitKw: number; marginKw: number };
  set capacitySettings(value: { limitKw: number; marginKw: number });
  get capacityDryRun(): boolean;
  set capacityDryRun(value: boolean);
  get operatingMode(): string;
  set operatingMode(value: string);
  get modeAliases(): Record<string, string>;
  set modeAliases(value: Record<string, string>);
  get capacityPriorities(): Record<string, Record<string, number>>;
  set capacityPriorities(value: Record<string, Record<string, number>>);
  get modeDeviceTargets(): Record<string, Record<string, number>>;
  set modeDeviceTargets(value: Record<string, Record<string, number>>);
  get controllableDevices(): Record<string, boolean>;
  set controllableDevices(value: Record<string, boolean>);
  get managedDevices(): Record<string, boolean>;
  set managedDevices(value: Record<string, boolean>);
  get budgetExemptDevices(): Record<string, boolean>;
  set budgetExemptDevices(value: Record<string, boolean>);
  get deviceControlProfiles(): DeviceControlProfiles;
  set deviceControlProfiles(value: DeviceControlProfiles);
  get deviceCommunicationModels(): Record<string, 'local' | 'cloud'>;
  set deviceCommunicationModels(value: Record<string, 'local' | 'cloud'>);
  get experimentalEvSupportEnabled(): boolean;
  set experimentalEvSupportEnabled(value: boolean);
  get shedBehaviors(): Record<string, ShedBehavior>;
  set shedBehaviors(value: Record<string, ShedBehavior>);
  get debugLoggingTopics(): Set<DebugLoggingTopic>;
  set debugLoggingTopics(value: Set<DebugLoggingTopic>);
  get defaultComputeDynamicSoftLimit(): (() => number) | undefined;
  set defaultComputeDynamicSoftLimit(value: (() => number) | undefined);
  get lastKnownPowerKw(): Record<string, number>;
  get expectedPowerKwOverrides(): Record<string, { kw: number; ts: number }>;
  get lastPositiveMeasuredPowerKw(): Record<string, { kw: number; ts: number }>;
  get lastNotifiedOperatingMode(): string;
  set lastNotifiedOperatingMode(value: string);
  get powerSampleRebuildState(): PowerSampleRebuildState;
  set powerSampleRebuildState(value: PowerSampleRebuildState);
  get latestTargetSnapshot(): TargetDeviceSnapshot[];
  get priceOptimizationEnabled(): boolean;
  get priceOptimizationSettings(): Record<string, PriceOptimizationSettings>;
  capacityGuard?: CapacityGuard;
  dailyBudgetService?: DailyBudgetService;
  deviceDiagnosticsService?: DeviceDiagnosticsService;
  priceCoordinator?: PriceCoordinator;
  deviceManager?: DeviceManager;
  planEngine?: PlanEngine;
  planService?: PlanService;
  readonly planRebuildScheduler: PlanRebuildScheduler;
  readonly snapshotHelpers: AppSnapshotHelpers;
  readonly homeyEnergyHelpers: AppHomeyEnergyHelpers;
  readonly deviceControlHelpers: AppDeviceControlHelpers;
  readonly timers: TimerRegistry;
};
