/* Generated by `npm run build:widgets`. Do not edit directly. */
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// widgets/create_smart_task/src/createSmartTaskWidgetPayload.ts
var createSmartTaskWidgetPayload_exports = {};
__export(createSmartTaskWidgetPayload_exports, {
  EMPTY_NO_DEVICES_HINT: () => EMPTY_NO_DEVICES_HINT,
  EMPTY_NO_DEVICES_SUBTITLE: () => EMPTY_NO_DEVICES_SUBTITLE,
  buildCreateSmartTaskDevicesPayload: () => buildCreateSmartTaskDevicesPayload
});
module.exports = __toCommonJS(createSmartTaskWidgetPayload_exports);

// packages/shared-domain/src/deadlineLabels.ts
var PENDING_REASON_MISSING_CAPACITY_COPY = "Learning energy use \u2014 needs power readings from this device.";
var SMART_TASK_LIST_STATUS_LABELS = {
  building_plan: "Building plan\u2026",
  queued: "Scheduled",
  paused_unplugged: "Paused \u2014 unplugged",
  on_track: "On track",
  at_risk: "At risk",
  cannot_meet: "Cannot finish",
  satisfied: "Satisfied"
};
var SMART_TASK_WIDGET_STATUS_LABELS = {
  ...SMART_TASK_LIST_STATUS_LABELS,
  paused_unplugged: "Unplugged"
};
var CREATE_SMART_TASK_WIDGET_COPY = {
  // Step 1 — device picker.
  pickDeviceTitle: "New smart task",
  pickDevicePrompt: "Choose a device",
  emptyNoDevices: "No eligible devices",
  // Warmer than a bare capability list: name the device kinds AND the next
  // action, so a user with nothing yet knows exactly how to make a device
  // appear here rather than hitting a dead end.
  emptyNoDevicesHint: "Add a thermostat, water heater, or EV charger in Homey and it\u2019ll appear here.",
  loadError: "Could not load devices. Try again later.",
  // Shown while the widget is still wiring up to the Homey app (the SDK bridge
  // hasn't supplied a real API client yet). Distinct from `loadError` (a real
  // fetch that failed): this is a transient "not ready yet" state that resolves
  // on its own once the bridge connects, so it reads as loading rather than a
  // hard failure. The widget never shows canned sample devices on a real boot,
  // and keeps Create disabled until a real client is present, so a user can
  // never see a false "Created" while running against sample data.
  notReady: "Connecting to Homey\u2026",
  // Step 2 — goal + ready-by.
  goalLabel: "Goal",
  readyByLabel: "Ready by",
  previewButton: "Preview",
  // Step 3 — preview + confirm.
  previewTitle: "Preview",
  // Canonical "Scheduled" vocabulary (matches `SMART_TASK_LIST_STATUS_LABELS`
  // / `SMART_TASK_LIST_ROW_LABELS` and the terminology guide) rather than the
  // one-off noun "Runs": the preview's when-window is the same concept the list
  // chip names.
  scheduledLabel: "Scheduled",
  energyLabel: "Energy",
  costLabel: "Cost",
  // The estimate is computed in isolation for this one candidate — surface the
  // caveat honestly rather than implying a guarantee (the
  // `DeferredObjectivePlanPreview` contract documents the same in-isolation
  // direction-of-error). Kept short for the 320–480 px widget.
  estimateCaveat: "Estimate \u2014 the actual run may differ as prices and other tasks change.",
  createButton: "Create smart task",
  backButton: "Back",
  // Shown when the preview can't be projected and the backend did not provide a
  // more specific missing-input reason. Distinct from a hard error. Avoids the
  // reserved "plan" noun (`feedback_terminology_plan_vs_deadline`).
  previewUnavailable: "Can\u2019t preview this yet \u2014 PELS needs more current data for this window.",
  // Shown specifically when the device has no learned energy profile yet
  // (`unavailableReason === 'needs_observation'`): there is no temperature
  // bootstrap rate, so PELS can't estimate the run until it has watched the
  // device draw power. Tells the user the two ways to make that happen rather
  // than (falsely) blaming prices. Names the real per-device toggle
  // ("Power-limit control", see settings-ui `devices.ts`) so the remedy is
  // actionable. Avoids the reserved "plan" noun.
  previewNeedsObservation: "PELS needs to observe this device in action before it can be used for a smart task. Either let it run normally for a while, or turn on Power-limit control for it.",
  // Shown when the candidate's goal is already met (preview `status: 'satisfied'`
  // → zero scheduled hours): there is nothing to schedule, so explain that
  // honestly rather than reusing the no-prices line. Uses the canonical "goal"
  // noun (matches `goalLabel`) and avoids the reserved "plan" noun.
  previewSatisfied: "This goal is already met \u2014 nothing to schedule.",
  // Pending state on the Create button while the /create round-trip is in
  // flight. Distinct from `created` (the confirmed-success label): the button
  // must read as work-in-progress, never as success, until a `{ ok: true }`
  // create actually lands — otherwise a still-pending or later-failed create
  // would have flashed "Smart task created" before anything was persisted.
  creating: "Creating\u2026",
  // Shown briefly after a successful create before the widget resets.
  created: "Smart task created",
  // Generic submit failure (rejected candidate / transient SDK miss).
  createError: "Could not create the smart task. Check the goal and try again.",
  // A transient settings-write refusal (`write_conflict`): the goal was valid,
  // the persist just flaked, so the data is safe and a plain retry resolves it.
  // Distinct from `createError` so we never tell the user to "check the goal"
  // for a failure that has nothing to do with their input.
  writeConflict: "Could not save the smart task just now. Try again.",
  // The previewed "Ready by" time slipped into the past between previewing and
  // confirming (the user lingered past the chosen minute). The create is
  // rejected rather than silently rolled to the next day so the created task
  // can never disagree with the window the preview promised — re-previewing
  // resolves a fresh future deadline. Retryable, not a hard failure.
  deadlinePassed: "That ready-by time just passed. Preview again to pick a fresh time.",
  // Step 2 — optional "Extra permissions" disclosure. Collapsed and OFF by
  // default; a user opts in per task. The section hint stays honest about scope
  // (only to hit THIS deadline) and never implies more total power or a raised
  // cap (`feedback_hard_cap_is_physical`). The two toggle labels themselves come
  // from `SMART_TASK_EXTRA_PERMISSION_LABELS` so the widget, the settings-UI
  // breadcrumb, and runtime logs all read identically.
  extraPermissionsTitle: "Extra permissions",
  extraPermissionsHint: "Off unless you turn them on \u2014 only used to hit this deadline.",
  // Read-only context shown above the toggles when the device ALREADY has
  // standing permissions. Deliberately route-agnostic ("Already allowed:", not
  // "set via Flow"): the grant can come from a Flow card OR the rescue-boost lane
  // ("Get power now" / "Let it run now"), so naming a single route would be wrong
  // for the other — and this string also feeds runtime log breadcrumbs, so a false
  // attribution would mislead there too. Names the scope-current state, not how it
  // got there. Joined with the formatted permission value via
  // `formatSmartTaskStandingPermissionsLine`; reuses the same canonical permission
  // labels as the settings-UI breadcrumb so the wording can't drift.
  standingPermissionsPrefix: "Already allowed:",
  // Shown under the limit-lower-priority toggle when it is disabled: that
  // permission only has any effect alongside the budget one, so it is gated on it.
  limitLowerPriorityNeedsBudget: "Turn on \u201CMay go over daily budget\u201D to use this.",
  // Shown in the preview when the in-isolation projection returns a real planner
  // verdict that the deadline may not be met — `cannot_meet` (won't make it) or
  // `at_risk` (might not). Surfaced as a prominent warning so a user never
  // commits an unreachable ready-by believing it is fine. The estimate
  // UNDERSTATES this risk (it projects the candidate in isolation — see the
  // `DeferredObjectivePlanPreview` contract), so the copy is a plain warning, not
  // a soft hint. Distinct from `previewUnavailable`, which is a missing-price /
  // projection gap rather than a feasibility verdict.
  cannotMeet: "Cannot finish \u2014 not enough usable time before this ready-by time.",
  atRisk: "At risk \u2014 this may need most of the available window."
};
var PREVIEW_UNAVAILABLE_COPY_BY_REASON = {
  invalid_deadline: "Can\u2019t preview this ready-by time yet.",
  invalid_session: "Can\u2019t preview this yet \u2014 plug the EV in to start.",
  missing_capacity: "Can\u2019t preview this yet \u2014 PELS needs power readings from this device.",
  missing_device: "Can\u2019t preview this yet \u2014 PELS can\u2019t find this device.",
  needs_observation: CREATE_SMART_TASK_WIDGET_COPY.previewNeedsObservation,
  missing_prices: "Can\u2019t preview this yet \u2014 prices through this window are not available yet.",
  missing_reading: "Can\u2019t preview this yet \u2014 PELS needs a current device reading.",
  price_feature_disabled: "Can\u2019t preview this yet \u2014 price-aware planning is off.",
  progress_stale: "Can\u2019t preview this yet \u2014 PELS needs a fresher device reading.",
  unknown: CREATE_SMART_TASK_WIDGET_COPY.previewUnavailable
};
var resolveBuildingPlanChipTone = () => "info";
var resolvePausedUnpluggedChipTone = () => "warn";
var SMART_TASK_LIST_STATUS_CHIP_VARIANT = {
  building_plan: resolveBuildingPlanChipTone(),
  queued: "muted",
  paused_unplugged: resolvePausedUnpluggedChipTone(),
  on_track: "ok",
  at_risk: "warn",
  cannot_meet: "alert",
  satisfied: "ok"
};
var SMART_TASK_LIST_READY_BY_STATUS_WORD = {
  building_plan: null,
  queued: null,
  // The inline word is joined to the timestamp with an em-dash separator
  // ("Ready by … — <word>"). For paused we use the compressed widget label
  // ('Unplugged') rather than the full chip label ('Paused — unplugged'): the
  // latter carries its own em-dash, which would render a confusing double-dash
  // ("… — Paused — unplugged") on the Ready-by line. The chip still shows the
  // full label; this is the same sanctioned shared-domain string, not a new
  // variant.
  paused_unplugged: SMART_TASK_WIDGET_STATUS_LABELS.paused_unplugged,
  on_track: null,
  at_risk: SMART_TASK_LIST_STATUS_LABELS.at_risk,
  cannot_meet: SMART_TASK_LIST_STATUS_LABELS.cannot_meet,
  satisfied: null
};
var SMART_TASK_LIST_ROW_LABELS = {
  target: "Target",
  starts: "Starts",
  readyBy: "Ready by"
};
var SMART_TASK_WIDGET_TARGET_NOUN = SMART_TASK_LIST_ROW_LABELS.target;
var REVISION_REASON_TOOLTIP_LINE = {
  flow_card: "Updated after a flow card fired",
  prices_arrived: "Updated as prices became available",
  objective_changed: "Updated after the target changed",
  // Only fires when the planner consumed a newer price horizon than the
  // previous revision. `schedule_revised` carries internal replans.
  prices_revised: "Updated as new prices arrived",
  // Schedule shifted without a new price horizon — daily-budget pressure
  // moved a bucket, planStatus flipped, etc. Honest about the cause without
  // claiming a publication event.
  schedule_revised: "Updated as the schedule was revised",
  rate_refined: "Updated as rates were refined",
  flow_permission_changed: "Updated after a Flow changed what this smart task may do"
};
var SCHEDULE_REVISED_BASE = "Schedule revised";
var SCHEDULE_REVISED_BUDGET = `${SCHEDULE_REVISED_BASE} \u2014 daily budget shifted`;
var SCHEDULE_REVISED_RISK = `${SCHEDULE_REVISED_BASE} \u2014 risk changed`;
var SCHEDULE_REVISED_OPENED = `${SCHEDULE_REVISED_BASE} \u2014 cheaper hour opened`;
var withLastFetched = (base, lastFetchedShort) => lastFetchedShort ? `${base} Last price update: ${lastFetchedShort}.` : base;
var resolveQueuedHeadlineReason = (params) => {
  if (params.pricesShortOfDeadline) {
    return `Waiting for tomorrow\u2019s prices through ${params.deadlineTime}.`;
  }
  if (params.dailyBudgetExhausted) {
    return "Today\u2019s budget is full \u2014 next cheap window after midnight.";
  }
  return `Cheaper than now \u2014 starts at ${params.firstPlannedTime}.`;
};
var CANNOT_MEET_RECOURSE = {
  openBudget: { label: "Open Budget", targetTab: "budget" },
  openOverview: { label: "Adjust device", targetTab: "overview" }
};
var OVERVIEW_DEVICE_RECOURSE_BASE = { label: "Open device in Overview", targetTab: "overview" };
var overviewDeviceRecourse = (deviceId) => ({ ...OVERVIEW_DEVICE_RECOURSE_BASE, deviceId });
var awaitingHorizonCopy = (kindNoun) => ((ctx) => {
  const isFlow = ctx.priceSource === "external_flow";
  const body = isFlow ? `PELS needs prices through the deadline before it can build a ${kindNoun}. In flow price mode, prices arrive only when a Flow calls the \u201CSet external prices (tomorrow)\u201D action. Check the Flow that publishes prices if this message stays up after tomorrow\u2019s prices should have arrived.` : `PELS will build a ${kindNoun} as soon as prices through the deadline are available.`;
  return {
    headline: isFlow ? "Waiting for tomorrow\u2019s prices from your Flow" : "Waiting for tomorrow\u2019s prices",
    body: withLastFetched(body, ctx.lastFetchedShort),
    // Avoid restating "Waiting for tomorrow’s prices" from the headline; the
    // panic-visitor's actionable detail is the horizon time the planner
    // needs to cover.
    headlineReason: `Need prices through ${ctx.deadlineTime} before the smart task can start.`,
    recourse: null
  };
});
var deviceDataMissingResolver = (kind) => (ctx) => ({
  headline: kind.headline,
  body: kind.body,
  headlineReason: `PELS can\u2019t read the ${kind.readingNoun} from ${ctx.deviceName.trim() || kind.fallbackDeviceNoun}.`,
  recourse: overviewDeviceRecourse(ctx.deviceId)
});
var [MISSING_CAPACITY_HEADLINE, MISSING_CAPACITY_BODY_FRAGMENT] = PENDING_REASON_MISSING_CAPACITY_COPY.split(" \u2014 ");
var MISSING_CAPACITY_BODY = `${MISSING_CAPACITY_BODY_FRAGMENT[0].toUpperCase()}${MISSING_CAPACITY_BODY_FRAGMENT.slice(1)}`;
var HEATER_DEVICE_DATA_MISSING = deviceDataMissingResolver({
  headline: "Waiting for a reading from the device",
  body: "PELS needs a current temperature, a useful capacity, or a recent observation from this heater before it can plan the smart task.",
  readingNoun: "current temperature",
  fallbackDeviceNoun: "the heater"
});
var EV_DEVICE_DATA_MISSING = deviceDataMissingResolver({
  headline: "Waiting for a reading from the EV",
  body: "PELS needs a current state of charge, a charge rate, or a recent observation from this EV before it can plan the smart task.",
  readingNoun: "state of charge",
  fallbackDeviceNoun: "the EV"
});
var DEADLINE_LABELS = {
  temperature: {
    kindChipLabel: "Temperature",
    activeChipLabel: "Heating",
    sectionLabel: "Heating smart task",
    liveStateChipLabel: {
      active: "Heating",
      building_plan: "Building plan\u2026",
      queued: "Scheduled",
      // Thermal devices can't be unplugged; the variant is unreachable here
      // and falls back to the generic scheduled copy if the resolver ever
      // hands a stale value through.
      paused_unplugged: "Scheduled",
      ok: "On track"
    },
    atRiskChipLabel: SMART_TASK_LIST_STATUS_LABELS.at_risk,
    cannotMeetChipLabel: "Cannot finish",
    deviceSeriesName: "Heating",
    originalDeviceSeriesName: "Original Heating",
    actualDeviceSeriesName: "Measured Heating",
    backgroundSeriesName: "Background usage",
    progressSeriesName: "Temperature",
    planTooltipIdle: "Idle",
    // Thermal `invalid_session` is unreachable today (heaters can't be
    // unplugged); we map it to `device_data_missing` so a future diagnostic
    // can't leak EV-specific copy. `missing_capacity` is the cold-start
    // "learning energy profile" state — no shipped bootstrap kWh/°C — and
    // recourse lands on Overview where the user can verify the heater is
    // actually running and reporting power.
    pendingHeroByReason: {
      awaiting_horizon_plan: awaitingHorizonCopy("heat plan"),
      price_feature_disabled: () => ({
        headline: "Price-aware optimisation is off",
        body: "Enable price-aware optimisation in Settings \u2192 Electricity prices to compute a heat plan.",
        headlineReason: "Price-aware optimisation is off in Settings.",
        recourse: { label: "Open Settings", targetTab: "settings" }
      }),
      device_data_missing: HEATER_DEVICE_DATA_MISSING,
      invalid_session: HEATER_DEVICE_DATA_MISSING,
      // Cold-start `missing_capacity` collapses to a single user-facing line —
      // headline + metaLine combined parse as `PENDING_REASON_MISSING_CAPACITY_COPY`
      // ("Learning energy use — needs power readings from this device."). Earlier
      // copy split the explanation across body + headlineReason, which buried the
      // "give it power readings" lever in a paragraph. The pending-reason path
      // here intentionally addresses only `objective_missing_capacity`
      // (no-profile cold-start); the thermal `objective_missing_charge_rate`
      // fall-through still routes to this resolver via `THERMAL_LEARNING_CAPACITY_REASON_CODES`
      // in the recorder, which is the same "still learning" user state from
      // their point of view.
      missing_capacity: (ctx) => ({
        headline: MISSING_CAPACITY_HEADLINE,
        body: MISSING_CAPACITY_BODY,
        headlineReason: null,
        recourse: overviewDeviceRecourse(ctx.deviceId)
      })
    },
    unavailableByReason: {
      no_current_reading: {
        headline: "Waiting for the first temperature reading",
        body: "The schedule will appear once the device reports its current temperature."
      },
      already_satisfied: {
        headline: "Satisfied",
        body: "The current temperature already meets the smart task target. PELS will schedule it again if the temperature drops below target."
      }
    },
    // Drops the raw progress-unit delta ("Short by about 41.9 °C") that users
    // misread as a wild temperature anomaly. The underlying shortfall is energy
    // / time against the plan, not a raw temperature gap; the chip + headline
    // already say the verdict ("Cannot finish"); body states the cause and the
    // user-side levers. The hero meta line follows with the "Needs N kWh · Y
    // hours left · …" line via `formatMetaLine`, which is the right surface for
    // magnitude. Recourse copy names the two levers that aren't the daily
    // budget; the budget remedy is handled by the dedicated
    // `cannotMeetDailyBudgetExhausted` branch above.
    cannotMeetShortfall: () => "Not enough time for this target. Lower the target or move the deadline.",
    cannotMeetDailyBudgetExhausted: "Today's daily budget is fully booked. Lower it so future days reserve power earlier, or move the deadline.",
    cannotMeetRecourse: CANNOT_MEET_RECOURSE,
    resolveQueuedHeadlineReason,
    completedHero: {
      headline: "Smart task finished",
      body: "See Smart tasks for the outcome."
    },
    targetUnit: "\xB0C",
    planInputsCardTitle: "What PELS has learned",
    planInputsRateRowLabel: "Energy needed per \xB0C",
    planInputsMaxPowerRowLabel: "Device power used",
    perUnitRateUnit: "kWh/\xB0C",
    planInputsRateBootstrapNote: null,
    revisionReasonTooltipLine: REVISION_REASON_TOOLTIP_LINE
  },
  ev_soc: {
    kindChipLabel: "EV",
    activeChipLabel: "Charging",
    sectionLabel: "EV smart task",
    liveStateChipLabel: {
      active: "Charging",
      building_plan: "Building plan\u2026",
      queued: "Scheduled",
      paused_unplugged: "Paused \u2014 unplugged",
      ok: "On track"
    },
    atRiskChipLabel: SMART_TASK_LIST_STATUS_LABELS.at_risk,
    cannotMeetChipLabel: "Cannot finish",
    deviceSeriesName: "Charging",
    originalDeviceSeriesName: "Original Charging",
    actualDeviceSeriesName: "Measured Charging",
    backgroundSeriesName: "Background usage",
    progressSeriesName: "Charge level",
    planTooltipIdle: "Idle",
    // EV `invalid_session` is the plugged-out / discharging pause state. The
    // body already says "PELS will resume…", the headlineReason restates the
    // *cause* at headline height, and recourse is null because plugging in
    // is a physical action with no in-app tab to land on. EV
    // `missing_capacity` should never fire (bootstrap fallback exists); the
    // device-data-missing copy is kept as a safety net.
    pendingHeroByReason: {
      awaiting_horizon_plan: awaitingHorizonCopy("charging plan"),
      price_feature_disabled: () => ({
        headline: "Price-aware optimisation is off",
        body: "Enable price-aware optimisation in Settings \u2192 Electricity prices to compute a charging plan.",
        headlineReason: "Price-aware optimisation is off in Settings.",
        recourse: { label: "Open Settings", targetTab: "settings" }
      }),
      device_data_missing: EV_DEVICE_DATA_MISSING,
      invalid_session: () => ({
        headline: "Charging paused \u2014 EV unplugged",
        body: "PELS will resume the schedule once the EV is plugged in and reports a valid charging session.",
        headlineReason: "Charger reports the car isn\u2019t plugged in.",
        recourse: null
      }),
      missing_capacity: EV_DEVICE_DATA_MISSING
    },
    unavailableByReason: {
      no_current_reading: {
        headline: "Waiting for the first state-of-charge reading",
        body: "The schedule will appear once the EV reports its current state of charge."
      },
      already_satisfied: {
        headline: "Satisfied",
        body: "The EV is already at or above the smart task target. PELS will schedule it again if the state of charge drops below target."
      }
    },
    // EV mirrors the thermal copy: drop the raw % shortfall figure (users can
    // read it as "the car lost 30 % of charge") in favour of plain-language
    // recourse. The meta line continues to carry the energy/duration magnitude.
    cannotMeetShortfall: () => "Not enough time or charging power for this target. Lower the target or move the deadline.",
    cannotMeetDailyBudgetExhausted: "Today's daily budget is fully booked. Lower it so future days reserve power earlier, or move the deadline.",
    cannotMeetRecourse: CANNOT_MEET_RECOURSE,
    resolveQueuedHeadlineReason,
    completedHero: {
      headline: "Smart task finished",
      body: "See Smart tasks for the outcome."
    },
    targetUnit: "%",
    planInputsCardTitle: "What PELS has learned",
    planInputsRateRowLabel: "Energy needed per %",
    planInputsMaxPowerRowLabel: "Device power used",
    perUnitRateUnit: "kWh/%",
    planInputsRateBootstrapNote: "Estimated \u2014 refining as PELS observes charging.",
    revisionReasonTooltipLine: REVISION_REASON_TOOLTIP_LINE
  }
};
var deadlineLabels = (kind) => DEADLINE_LABELS[kind];
var EV_CARD_HOUR_MS = 60 * 60 * 1e3;
var SAMPLE_STALE_THRESHOLD_MS = 24 * 60 * 60 * 1e3;
var ONE_MINUTE_MS = 60 * 1e3;
var ONE_HOUR_MS = 60 * ONE_MINUTE_MS;

// packages/shared-domain/src/smartTaskDeviceKind.ts
var isEvCharger = (device) => device.deviceClass === "evcharger";
var supportsTemperatureGoal = (device) => device.deviceType === "temperature" || (device.targets?.length ?? 0) > 0;
var resolveSmartTaskDeviceKind = (device) => {
  if (isEvCharger(device)) return "ev_soc";
  if (supportsTemperatureGoal(device)) return "temperature";
  return null;
};
var TEMPERATURE_FALLBACK_MIN = 5;
var TEMPERATURE_FALLBACK_MAX = 95;
var TEMPERATURE_FALLBACK_STEP = 0.5;
var isFiniteNumber = (value) => typeof value === "number" && Number.isFinite(value);
var resolveSmartTaskGoalBounds = (device, kind) => {
  const unit = deadlineLabels(kind).targetUnit;
  if (kind === "ev_soc") {
    return { unit, min: 1, max: 100, step: 1 };
  }
  const target = device.targets?.[0];
  const min = isFiniteNumber(target?.min) ? target.min : TEMPERATURE_FALLBACK_MIN;
  const max = isFiniteNumber(target?.max) ? target.max : TEMPERATURE_FALLBACK_MAX;
  const step = isFiniteNumber(target?.step) && target.step > 0 ? target.step : TEMPERATURE_FALLBACK_STEP;
  return { unit, min, max, step };
};
var resolveSmartTaskCurrentValue = (device, kind) => {
  if (kind === "temperature") {
    return isFiniteNumber(device.currentTemperature) ? device.currentTemperature : null;
  }
  const percent = device.stateOfCharge?.percent;
  return isFiniteNumber(percent) ? percent : null;
};
var DEFAULT_EV_TARGET_PERCENT = 80;
var DEFAULT_TEMPERATURE_TARGET_C = 60;
var resolveSmartTaskDefaultGoal = (params) => {
  const { kind, bounds, currentValue } = params;
  const commonCase = kind === "ev_soc" ? DEFAULT_EV_TARGET_PERCENT : DEFAULT_TEMPERATURE_TARGET_C;
  const target = currentValue !== null ? Math.max(commonCase, currentValue) : commonCase;
  const clamped = Math.min(bounds.max, Math.max(bounds.min, target));
  const snapped = bounds.min + Math.round((clamped - bounds.min) / bounds.step) * bounds.step;
  return Math.min(bounds.max, Math.max(bounds.min, Math.round(snapped * 100) / 100));
};

// packages/shared-domain/src/smartTaskDevicePickerOrder.ts
var SMART_TASK_DEVICE_GROUP_ORDER = [
  "heating",
  "ev_charger"
];
var resolveSmartTaskDeviceGroup = (device) => device.kind === "ev_soc" ? "ev_charger" : "heating";
var GROUP_RANK = Object.fromEntries(
  SMART_TASK_DEVICE_GROUP_ORDER.map((group, index) => [group, index])
);
var groupRank = (group) => GROUP_RANK[group];
var compareSmartTaskPickerRows = (a, b) => {
  const byGroup = groupRank(a.group) - groupRank(b.group);
  if (byGroup !== 0) return byGroup;
  return a.deviceName.localeCompare(b.deviceName);
};

// widgets/create_smart_task/src/createSmartTaskWidgetPayload.ts
var EMPTY_NO_DEVICES_SUBTITLE = CREATE_SMART_TASK_WIDGET_COPY.emptyNoDevices;
var EMPTY_NO_DEVICES_HINT = CREATE_SMART_TASK_WIDGET_COPY.emptyNoDevicesHint;
var buildDevice = (device, resolveStandingRescue) => {
  const kind = resolveSmartTaskDeviceKind(device);
  if (kind === null) return null;
  const bounds = resolveSmartTaskGoalBounds(device, kind);
  const currentValue = resolveSmartTaskCurrentValue(device, kind);
  const name = device.name?.trim();
  const standingRescue = resolveStandingRescue?.(device.id);
  return {
    deviceId: device.id,
    deviceName: name && name.length > 0 ? name : device.id,
    kind,
    group: resolveSmartTaskDeviceGroup({ kind }),
    unitSymbol: bounds.unit,
    goalMin: bounds.min,
    goalMax: bounds.max,
    goalStep: bounds.step,
    defaultGoal: resolveSmartTaskDefaultGoal({ kind, bounds, currentValue }),
    currentValue,
    // Gate-on-effect: the limit-lower-priority permission only changes the plan
    // for a stepped-load device at top priority (the planner's `fullyReserved`
    // floor is `priority === 1`). The stepped predicate mirrors app.ts
    // `deviceSupportsLimitLowerPriority`; the extra `priority === 1` keeps the
    // compose toggle from ever being offered where it would be a no-op.
    supportsLimitLowerPriority: device.controlModel === "stepped_load" && device.steppedLoadProfile?.model === "stepped_load" && device.priority === 1,
    // Read-only context for the compose screen's "Extra permissions" section so
    // the toggles read as additive on top of existing standing grants. Omitted
    // when the device has none (the section behaves as before).
    ...standingRescue ? { standingRescue } : {}
  };
};
var buildCreateSmartTaskDevicesPayload = (input) => {
  const devices = input.devices.map((device) => buildDevice(device, input.resolveStandingRescue)).filter((device) => device !== null).sort(compareSmartTaskPickerRows);
  if (devices.length === 0) {
    return { state: "empty", subtitle: EMPTY_NO_DEVICES_SUBTITLE, hint: EMPTY_NO_DEVICES_HINT };
  }
  return { state: "ready", devices };
};
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  EMPTY_NO_DEVICES_HINT,
  EMPTY_NO_DEVICES_SUBTITLE,
  buildCreateSmartTaskDevicesPayload
});
