// AUTO-GENERATED by scripts/build-nettleie-fallback.mjs — DO NOT EDIT BY HAND.
// Run `npm run build:nettleie-fallback` to refresh.
//
// Static, last-resort fallback for Norwegian grid tariffs (nettleie), used only
// when the NVE API is unreachable and no live tariff has been cached yet.
//
// Generated: 2026-06-03 | Operators: 75
// Source: Fri Nettleie (https://github.com/kraftsystemet/fri-nettleie), CC-BY-4.0.
// GLN→organisasjonsnr mapping from Elhub reference data.
//
// Prices are energy-fee (energiledd) in øre/kWh, EXCLUDING VAT and other taxes.
// 'hours' are the local hours-of-day the exception applies to; 'months' (1-12)
// and 'dayTypes' (fri-nettleie day tokens) narrow when it applies — omitted means
// "always". Resolution to a concrete day happens in staticGridTariffFallback.ts.

export interface NettleieFallbackException {
  /** Local hours-of-day (0-23) the exception price applies to. */
  readonly hours: readonly number[];
  /** Months (1-12) the exception applies to; omitted means all months. */
  readonly months?: readonly number[];
  /** fri-nettleie day tokens (e.g. 'virkedag', 'helg'); omitted means all days. */
  readonly dayTypes?: readonly string[];
  /** Replacement energy fee in øre/kWh, ex VAT. */
  readonly price: number;
}

export interface NettleieFallbackTariff {
  /** Base energy fee in øre/kWh, ex VAT (applies when no exception matches). */
  readonly basePrice: number;
  readonly exceptions: readonly NettleieFallbackException[];
}

export type NettleieFallbackTariffGroup = 'Husholdning' | 'Hytter og fritidshus';

export interface NettleieFallbackOperator {
  readonly name: string;
  readonly tariffs: Partial<Record<NettleieFallbackTariffGroup, NettleieFallbackTariff>>;
}

export const NETTLEIE_FALLBACK_GENERATED_AT = '2026-06-03';

export const NETTLEIE_FALLBACK_BY_ORGNR: Readonly<Record<string, NettleieFallbackOperator>> = {
  "824368082": {
    "name": "Vang Energiverk AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 13,
        "exceptions": []
      },
      "Hytter og fritidshus": {
        "basePrice": 13,
        "exceptions": []
      }
    }
  },
  "824701482": {
    "name": "Norefjell Nett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 15.08,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 22.53,
            "dayTypes": [
              "alle"
            ]
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 15.08,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 22.53,
            "dayTypes": [
              "alle"
            ]
          }
        ]
      }
    }
  },
  "824914982": {
    "name": "Jæren Everk AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 10,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 16,
            "dayTypes": [
              "ukedag"
            ]
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 10,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 16,
            "dayTypes": [
              "ukedag"
            ]
          }
        ]
      }
    }
  },
  "882783022": {
    "name": "Etna Nett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 18.59,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 25.55,
            "dayTypes": [
              "virkedag"
            ]
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 18.59,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 25.55,
            "dayTypes": [
              "virkedag"
            ]
          }
        ]
      }
    }
  },
  "912631532": {
    "name": "Linja AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 15.382,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 22.382
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 15.382,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 22.382
          }
        ]
      }
    }
  },
  "914385261": {
    "name": "Stram AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 4.11,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 14.11,
            "dayTypes": [
              "virkedag"
            ]
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 4.11,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 14.11,
            "dayTypes": [
              "virkedag"
            ]
          }
        ]
      }
    }
  },
  "915635857": {
    "name": "Fagne AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 20,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 28,
            "dayTypes": [
              "ukedag"
            ]
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 20,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 28,
            "dayTypes": [
              "ukedag"
            ]
          }
        ]
      }
    }
  },
  "916319908": {
    "name": "Vevig AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 15.81,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 25.21,
            "dayTypes": [
              "alle"
            ]
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 15.81,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 25.21,
            "dayTypes": [
              "alle"
            ]
          }
        ]
      }
    }
  },
  "916763476": {
    "name": "Tinfos AS Nett",
    "tariffs": {
      "Husholdning": {
        "basePrice": 19,
        "exceptions": []
      },
      "Hytter og fritidshus": {
        "basePrice": 19,
        "exceptions": []
      }
    }
  },
  "917424799": {
    "name": "Linea AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 13.5,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 23.5,
            "dayTypes": [
              "virkedag"
            ]
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 13.5,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 23.5,
            "dayTypes": [
              "virkedag"
            ]
          }
        ]
      }
    }
  },
  "917743193": {
    "name": "Asker Nett",
    "tariffs": {
      "Husholdning": {
        "basePrice": 15.87,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 23.87
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 15.87,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 23.87
          }
        ]
      }
    }
  },
  "917856222": {
    "name": "Midtnett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 18.86,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 23.86,
            "dayTypes": [
              "alle"
            ]
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 18.86,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 23.86,
            "dayTypes": [
              "alle"
            ]
          }
        ]
      }
    }
  },
  "917983550": {
    "name": "Noranett Hadsel AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 9,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 14
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 9,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 14
          }
        ]
      }
    }
  },
  "918312730": {
    "name": "Enida AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 21,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 27,
            "dayTypes": [
              "ukedag"
            ]
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 21,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 27,
            "dayTypes": [
              "ukedag"
            ]
          }
        ]
      }
    }
  },
  "918999361": {
    "name": "Tendranett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 20.35,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 25.87
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 20.35,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 25.87
          }
        ]
      }
    }
  },
  "919173122": {
    "name": "Meløy Nett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 17.4,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 27.4
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 17.4,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 27.4
          }
        ]
      }
    }
  },
  "919415096": {
    "name": "Indre Hordaland Kraftnett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 29,
        "exceptions": []
      },
      "Hytter og fritidshus": {
        "basePrice": 29,
        "exceptions": []
      }
    }
  },
  "919884452": {
    "name": "Viermie AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 16.4,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 22.8,
            "dayTypes": [
              "alle"
            ]
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 16.4,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 22.8,
            "dayTypes": [
              "alle"
            ]
          }
        ]
      }
    }
  },
  "921680554": {
    "name": "Noranett Andøy AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 16.4,
        "exceptions": []
      },
      "Hytter og fritidshus": {
        "basePrice": 16.4,
        "exceptions": []
      }
    }
  },
  "921683057": {
    "name": "Vissi AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 13,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 29
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 13,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 29
          }
        ]
      }
    }
  },
  "921688679": {
    "name": "Nettselskapet AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 1.6,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 11.6,
            "months": [5, 6, 7, 8, 9, 10]
          },
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 12.7,
            "months": [1, 2, 3, 4, 11, 12]
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 1.6,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 11.6,
            "months": [5, 6, 7, 8, 9, 10]
          },
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 12.7,
            "months": [1, 2, 3, 4, 11, 12]
          }
        ]
      }
    }
  },
  "922694435": {
    "name": "Straumnett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 15.96,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 20.96,
            "dayTypes": [
              "alle"
            ]
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 15.96,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 20.96,
            "dayTypes": [
              "alle"
            ]
          }
        ]
      }
    }
  },
  "923050612": {
    "name": "Føie AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 9.998,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 16.502
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 9.998,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 16.502
          }
        ]
      }
    }
  },
  "923152601": {
    "name": "Kystnett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 18,
        "exceptions": []
      },
      "Hytter og fritidshus": {
        "basePrice": 18,
        "exceptions": []
      }
    }
  },
  "923354204": {
    "name": "Fjellnett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 12.9,
        "exceptions": []
      },
      "Hytter og fritidshus": {
        "basePrice": 12.9,
        "exceptions": []
      }
    }
  },
  "923436596": {
    "name": "Klive AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 17.632,
        "exceptions": []
      },
      "Hytter og fritidshus": {
        "basePrice": 17.632,
        "exceptions": []
      }
    }
  },
  "923488960": {
    "name": "Høland og Setskog Elverk AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 17.5,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 22.5,
            "dayTypes": [
              "virkedag"
            ]
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 17.5,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 22.5,
            "dayTypes": [
              "virkedag"
            ]
          }
        ]
      }
    }
  },
  "923789324": {
    "name": "Haringnett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 16.5,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 24.5,
            "dayTypes": [
              "ukedag"
            ]
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 16.5,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 24.5,
            "dayTypes": [
              "ukedag"
            ]
          }
        ]
      }
    }
  },
  "923819177": {
    "name": "S-NETT AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 21.41,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 26.4,
            "dayTypes": [
              "alle"
            ]
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 21.41,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 26.4,
            "dayTypes": [
              "alle"
            ]
          }
        ]
      }
    }
  },
  "923833706": {
    "name": "Lysna AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 24,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 32
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 24,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 32
          }
        ]
      }
    }
  },
  "923934138": {
    "name": "Bømlo Kraftnett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 29,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 35.5
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 29,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 35.5
          }
        ]
      }
    }
  },
  "923993355": {
    "name": "Area Nett AS - Område 1- NettiNord",
    "tariffs": {
      "Husholdning": {
        "basePrice": 26.89,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 29.89,
            "months": [1, 2, 3]
          }
        ]
      }
    }
  },
  "924004150": {
    "name": "Havnett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 29.72,
        "exceptions": []
      },
      "Hytter og fritidshus": {
        "basePrice": 29.72,
        "exceptions": []
      }
    }
  },
  "924330678": {
    "name": "Netera AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 20,
        "exceptions": []
      },
      "Hytter og fritidshus": {
        "basePrice": 20,
        "exceptions": []
      }
    }
  },
  "924527994": {
    "name": "Breheim Nett",
    "tariffs": {
      "Husholdning": {
        "basePrice": 6.502,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 14.502
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 6.502,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 14.502
          }
        ]
      }
    }
  },
  "924619260": {
    "name": "Sygnir AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 22.05,
        "exceptions": []
      },
      "Hytter og fritidshus": {
        "basePrice": 22.05,
        "exceptions": []
      }
    }
  },
  "924862602": {
    "name": "DE Nett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 23.6,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 26.6,
            "months": [4, 5, 6, 7, 8, 9]
          },
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 31.4,
            "months": [1, 2, 3, 10, 11, 12]
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 23.6,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 26.6,
            "months": [4, 5, 6, 7, 8, 9]
          },
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 31.4,
            "months": [1, 2, 3, 10, 11, 12]
          }
        ]
      }
    }
  },
  "924940379": {
    "name": "Stannum AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 22.01,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 25.01,
            "dayTypes": [
              "alle"
            ]
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 22.01,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 25.01,
            "dayTypes": [
              "alle"
            ]
          }
        ]
      }
    }
  },
  "925017809": {
    "name": "RK Nett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 20.14,
        "exceptions": []
      },
      "Hytter og fritidshus": {
        "basePrice": 20.14,
        "exceptions": []
      }
    }
  },
  "925067911": {
    "name": "R-Nett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 16.87,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 26.47
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 16.87,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 26.47
          }
        ]
      }
    }
  },
  "925336637": {
    "name": "Alut AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 12.1,
        "exceptions": []
      },
      "Hytter og fritidshus": {
        "basePrice": 12.1,
        "exceptions": []
      }
    }
  },
  "925354813": {
    "name": "Straumen Nett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 18.304,
        "exceptions": []
      },
      "Hytter og fritidshus": {
        "basePrice": 18.304,
        "exceptions": []
      }
    }
  },
  "925549738": {
    "name": "Føre AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 19.29,
        "exceptions": []
      },
      "Hytter og fritidshus": {
        "basePrice": 19.29,
        "exceptions": []
      }
    }
  },
  "925668389": {
    "name": "Mellom AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 23.47,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 29.77
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 23.47,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 29.77
          }
        ]
      }
    }
  },
  "926377841": {
    "name": "Romsdalsnett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 20.72,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 30.72,
            "dayTypes": [
              "ukedag"
            ]
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 20.72,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 30.72,
            "dayTypes": [
              "ukedag"
            ]
          }
        ]
      }
    }
  },
  "933584801": {
    "name": "Mostraum Nett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 39,
        "exceptions": []
      },
      "Hytter og fritidshus": {
        "basePrice": 39,
        "exceptions": []
      }
    }
  },
  "953181606": {
    "name": "Bindal Kraftlag Nett",
    "tariffs": {
      "Husholdning": {
        "basePrice": 21.3,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 26.3
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 21.3,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 26.3
          }
        ]
      }
    }
  },
  "953681781": {
    "name": "Griug AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 12.32,
        "exceptions": []
      },
      "Hytter og fritidshus": {
        "basePrice": 12.32,
        "exceptions": []
      }
    }
  },
  "955996836": {
    "name": "Vest-Telemark Kraftlag AS Nett",
    "tariffs": {
      "Husholdning": {
        "basePrice": 25,
        "exceptions": []
      },
      "Hytter og fritidshus": {
        "basePrice": 25,
        "exceptions": []
      }
    }
  },
  "966731508": {
    "name": "Everket AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 19.2,
        "exceptions": []
      },
      "Hytter og fritidshus": {
        "basePrice": 19.2,
        "exceptions": []
      }
    }
  },
  "967670170": {
    "name": "Uvdal Kraftforsyning",
    "tariffs": {
      "Husholdning": {
        "basePrice": 15.12,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 23.12
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 15.12,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 23.12
          }
        ]
      }
    }
  },
  "968168134": {
    "name": "Vestall AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 3,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 6
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 3,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 6
          }
        ]
      }
    }
  },
  "971058854": {
    "name": "Barents Nett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 11.32,
        "exceptions": []
      },
      "Hytter og fritidshus": {
        "basePrice": 11.32,
        "exceptions": []
      }
    }
  },
  "971589752": {
    "name": "Føie AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 9.998,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 16.502
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 9.998,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 16.502
          }
        ]
      }
    }
  },
  "976944801": {
    "name": "BKK AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 10.5,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 28.77,
            "dayTypes": [
              "virkedag"
            ]
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 10.5,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 28.77,
            "dayTypes": [
              "virkedag"
            ]
          }
        ]
      }
    }
  },
  "977285712": {
    "name": "KE Nett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 8,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 18,
            "dayTypes": [
              "ukedag"
            ]
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 8,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 18,
            "dayTypes": [
              "ukedag"
            ]
          }
        ]
      }
    }
  },
  "978631029": {
    "name": "Tensio TS AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 10.206,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 20.702
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 10.206,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 20.702
          }
        ]
      }
    }
  },
  "979151950": {
    "name": "Arva AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 11.6,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 23.1
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 11.6,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 23.1
          }
        ]
      }
    }
  },
  "979379455": {
    "name": "Elinett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 14.64,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 22.64,
            "dayTypes": [
              "virkedag"
            ]
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 14.64,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 22.64,
            "dayTypes": [
              "virkedag"
            ]
          }
        ]
      }
    }
  },
  "979399901": {
    "name": "Vestmar Nett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 17.1,
        "exceptions": []
      },
      "Hytter og fritidshus": {
        "basePrice": 17.1,
        "exceptions": []
      }
    }
  },
  "979422679": {
    "name": "Lede AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 11.41,
        "exceptions": []
      },
      "Hytter og fritidshus": {
        "basePrice": 11.41,
        "exceptions": []
      }
    }
  },
  "979497482": {
    "name": "Elvenett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 11,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 20
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 11,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 20
          }
        ]
      }
    }
  },
  "980038408": {
    "name": "Lnett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 13.6,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 25.6,
            "dayTypes": [
              "virkedag"
            ]
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 13.6,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 25.6,
            "dayTypes": [
              "virkedag"
            ]
          }
        ]
      }
    }
  },
  "980234088": {
    "name": "Norgesnett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 13.29,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 20.26
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 13.29,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 20.26
          }
        ]
      }
    }
  },
  "980489698": {
    "name": "Elvia AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 12.99,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 20.99,
            "dayTypes": [
              "virkedag"
            ]
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 12.99,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 20.99,
            "dayTypes": [
              "virkedag"
            ]
          }
        ]
      }
    }
  },
  "980824586": {
    "name": "Nordvest Nett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 20.03,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 26.03
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 20.03,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 26.03
          }
        ]
      }
    }
  },
  "981915550": {
    "name": "Glitre Nett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 12.6,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 24.6
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 12.6,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 24.6
          }
        ]
      }
    }
  },
  "982897327": {
    "name": "Lucerna AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 13.32,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 19.32
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 13.32,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 19.32
          }
        ]
      }
    }
  },
  "982974011": {
    "name": "Glitre Nett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 12.6,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 24.6
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 12.6,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 24.6
          }
        ]
      }
    }
  },
  "985411131": {
    "name": "Noranett AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 0.8,
        "exceptions": []
      },
      "Hytter og fritidshus": {
        "basePrice": 0.8,
        "exceptions": []
      }
    }
  },
  "986347801": {
    "name": "Elmea AS Nett",
    "tariffs": {
      "Husholdning": {
        "basePrice": 25.6,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 37.9
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 25.6,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 37.9
          }
        ]
      }
    }
  },
  "987626844": {
    "name": "Føie AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 9.998,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 16.502
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 9.998,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 16.502
          }
        ]
      }
    }
  },
  "988807648": {
    "name": "Tensio TN AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 13.006,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 25.902,
            "dayTypes": [
              "alle"
            ]
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 13.006,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 25.902,
            "dayTypes": [
              "alle"
            ]
          }
        ]
      }
    }
  },
  "990892679": {
    "name": "Arva AS",
    "tariffs": {
      "Husholdning": {
        "basePrice": 11.6,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 23.1
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 11.6,
        "exceptions": [
          {
            "hours": [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            "price": 23.1
          }
        ]
      }
    }
  },
  "997712099": {
    "name": "Sør Aurdal Energi AS Nett",
    "tariffs": {
      "Husholdning": {
        "basePrice": 21.52,
        "exceptions": [
          {
            "hours": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
            "price": 25.52,
            "months": [1, 2, 3, 10, 11, 12]
          }
        ]
      },
      "Hytter og fritidshus": {
        "basePrice": 21.52,
        "exceptions": [
          {
            "hours": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
            "price": 25.52,
            "months": [1, 2, 3, 10, 11, 12]
          }
        ]
      }
    }
  }
};
