import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const widgetDir = path.join(rootDir, 'widgets', 'plan_budget');
const widgetSrcDir = path.join(widgetDir, 'src');

const generatedBanner = '/* Generated by `npm run build:widgets`. Do not edit directly. */';

await build({
  entryPoints: [
    path.join(widgetSrcDir, 'api.ts'),
    path.join(widgetSrcDir, 'planPriceWidgetPayload.ts'),
  ],
  outdir: widgetDir,
  outbase: widgetSrcDir,
  platform: 'node',
  format: 'cjs',
  target: 'node22',
  bundle: false,
  banner: {
    js: generatedBanner,
  },
});

await build({
  entryPoints: [path.join(widgetSrcDir, 'public', 'index.ts')],
  outfile: path.join(widgetDir, 'public', 'index.js'),
  bundle: true,
  format: 'iife',
  target: 'es2020',
  platform: 'browser',
  banner: {
    js: generatedBanner,
  },
});
