import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const generatedBanner = '/* Generated by `npm run build:widgets`. Do not edit directly. */';

const buildWidget = async ({ name, apiEntries }) => {
  const widgetDir = path.join(rootDir, 'widgets', name);
  const widgetSrcDir = path.join(widgetDir, 'src');

  await build({
    entryPoints: apiEntries.map((entry) => path.join(widgetSrcDir, entry)),
    outdir: widgetDir,
    outbase: widgetSrcDir,
    platform: 'node',
    format: 'cjs',
    target: 'node22',
    bundle: false,
    banner: { js: generatedBanner },
  });

  await build({
    entryPoints: [path.join(widgetSrcDir, 'public', 'index.ts')],
    outfile: path.join(widgetDir, 'public', 'index.js'),
    bundle: true,
    format: 'iife',
    target: 'es2020',
    platform: 'browser',
    banner: { js: generatedBanner },
  });
};

await buildWidget({
  name: 'plan_budget',
  apiEntries: ['api.ts', 'planPriceWidgetPayload.ts'],
});

await buildWidget({
  name: 'headroom',
  apiEntries: ['api.ts', 'headroomWidgetPayload.ts'],
});
