/* Generated by `npm run build:widgets`. Do not edit directly. */
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var api_exports = {};
__export(api_exports, {
  getHeadroom: () => getHeadroom
});
module.exports = __toCommonJS(api_exports);
var import_headroomWidgetPayload = require("./headroomWidgetPayload");
const PELS_STATUS_SETTING = "pels_status";
const readStatus = (raw) => {
  if (!raw || typeof raw !== "object") return null;
  return raw;
};
const getHeadroom = async ({ homey }) => {
  const status = readStatus(homey.settings.get(PELS_STATUS_SETTING));
  return (0, import_headroomWidgetPayload.buildHeadroomWidgetPayload)({ status });
};
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  getHeadroom
});
