/* Generated by `npm run build:widgets`. Do not edit directly. */
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var headroomWidgetPayload_exports = {};
__export(headroomWidgetPayload_exports, {
  EMPTY_SUBTITLE_DEFAULT: () => EMPTY_SUBTITLE_DEFAULT,
  buildHeadroomWidgetPayload: () => buildHeadroomWidgetPayload
});
module.exports = __toCommonJS(headroomWidgetPayload_exports);
const STALE_AFTER_MS = 90 * 1e3;
const EMPTY_SUBTITLE_DEFAULT = "No data yet";
const isFiniteNumber = (value) => typeof value === "number" && Number.isFinite(value);
const resolvePriceLevel = (value) => {
  if (value === "cheap") return "cheap";
  if (value === "expensive") return "expensive";
  if (value === "normal") return "normal";
  return "unknown";
};
const emptyPayload = (subtitle) => ({
  state: "empty",
  subtitle
});
const buildHeadroomWidgetPayload = (input) => {
  const status = input.status;
  if (!status) return emptyPayload(EMPTY_SUBTITLE_DEFAULT);
  const hourBudgetKw = isFiniteNumber(status.hourlyLimitKw) ? status.hourlyLimitKw : null;
  const headroomKw = isFiniteNumber(status.headroomKw) ? status.headroomKw : null;
  if (hourBudgetKw === null || headroomKw === null) return emptyPayload(EMPTY_SUBTITLE_DEFAULT);
  const currentKw = Math.max(0, hourBudgetKw - headroomKw);
  const shedCount = isFiniteNumber(status.devicesOff) ? Math.max(0, Math.round(status.devicesOff)) : 0;
  const priceLevel = resolvePriceLevel(status.priceLevel);
  const lastUpdate = isFiniteNumber(status.lastPowerUpdate) ? status.lastPowerUpdate : null;
  const nowMs = isFiniteNumber(input.nowMs) ? input.nowMs : Date.now();
  const timeStale = lastUpdate === null ? true : nowMs - lastUpdate > STALE_AFTER_MS;
  const stale = timeStale || status.powerKnown === false;
  const ready = {
    state: "ready",
    currentKw,
    hourBudgetKw,
    headroomKw,
    shedCount,
    priceLevel,
    stale
  };
  return ready;
};
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  EMPTY_SUBTITLE_DEFAULT,
  buildHeadroomWidgetPayload
});
